### ISSUE TITLE
Dynamic load balancing

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#10]
IPVS has this nice LB method http://kb.linuxvirtualserver.org/wiki/Dynamic_Feedback_Load_Balancing_Scheduling

Which is all the more relevent in case of distrubuted load balancing requirements of 'ClusterIP' and NodePort service types. Each node doing load balancing in round robin fashion has below limitations.

- if connections are mixture of short lived and long lived then we will end up in imbalance
- each node is acting on the local connection information it has. Due to distrubuted nature each node ends up doing load balancing without taking account of other nodes or global state

Here is the proposal:

- Implement monitor daemon that collects connection per endpoint from the node using contrack
- use in-memory distrubuted key-value store to persist the data.
- use the global view of connections to dynamically adjust the weights on each node

**Comment by bzub** [comment]
## Initial Implementation
The monitor daemon could weight real-servers with:
- Standard pod metrics provided by [Heapster](https://github.com/kubernetes/heapster)
- [Readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-readiness-probes) response times (if I can find that information exposed within kubernetes)

These kubernetes specific sources should alleviate the need for kube-router to maintain its own distributed data store to share weight variables.  For distributed configuration between kube-router instances a ConfigMap could be updated by a daemon/Pod responsible for calculating load-balancing weights, and kube-router could watch/consume that config.

## Research and Justification

There are several ways to get at least pod system-level load metrics in Kubernetes.  Application-level load metrics are also increasingly common in Kubernetes apps.  Especially true since it's a requirement to expose these metrics to use [Horizontal Pod Autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)

So here's some potential sources of load metrics that our monitor daemon could support:
- Prometheus scrape endpoints
- Pod and Container Readiness Probe events (response times)
- cAdvisor builtin and custom metrics
- Ingress Controller metrics (nginx, haproxy, traefik). In real use cases these could be independent or fed through Heapster/cAdvisor or Prometheus

Heapster is a relatively mature and popular cluster addon that collects from several of the above mentioned sources, so it could be a definitive source for system-level load metrics.  There is also an effort to standardize this type of information in the apiserver with a `metric` endpoint.  This API might be more apt for app-level load metrics.  More info on that in [this issue](https://github.com/kubernetes/features/issues/271), and implementation work in [this repo](https://github.com/kubernetes/metrics).

**Comment by murali-reddy** [comment]
Some interesting insights of distributed load balancing with all nodes running in active mode compared to traditional active-passive load balancer. Use of ECMP will be similar in effect to kube-router cluster IP being advertised by each node.

[Maglev: Google’s network load balancer.](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44824.pdf)

**Comment by SEJeff** [comment]
There is an [ingress](https://github.com/northwesternmutual/kanali/issues/56) doing something vaguely similar, but they are storing traffic stats in etcd.

**Comment by aauren** [comment]
Closing as stale
