### ISSUE TITLE
Assignment of podCIDRs

### ISSUE THREAD

**Issue by aceeric** [cloudnativelabs/kube-router#1034]
This is a question. Any help is appreciated.

I'm standing up a VirtualBox cluster based on kubernetes-the-hard-way but using kube-router via https://raw.githubusercontent.com/cloudnativelabs/kube-router/v1.1.1/daemonset/generic-kuberouter-all-features.yaml. The cluster has one controller and two workers.

I install the kubelet on each worker node. The `kubelet-config.yaml` has: `podCIDR: 10.200.1.0/24` for the first worker and `podCIDR: 10.200.2.0/24` for the second worker. When I start the cluster, I see this in the kubelet logs (this snippet is from the worker node that I explicitly configured for `10.200.1.0/24`):

```
$ journalctl -u kubelet | grep -i cidr'
flags.go:59] FLAG: --non-masquerade-cidr="10.0.0.0/8"
flags.go:59] FLAG: --pod-cidr=""
kuberuntime_manager.go:1006] updating runtime config through cri with podcidr 10.200.1.0/24
kubelet_network.go:77] Setting Pod CIDR:  -> 10.200.1.0/24
kuberuntime_manager.go:1006] updating runtime config through cri with podcidr 10.200.0.0/24
kubelet_network.go:77] Setting Pod CIDR: 10.200.1.0/24 -> 10.200.0.0/24
```

So, it gets set to "1" - matching the value in `kubelet-config.yaml`. Then set again to "0". And similarly, on the second worker, `10.200.2.0/24` gets overridden to `10.200.1.0/24` in 1-up fashion. Then:

```
kubectl get nodes -ocustom-columns='NAME:metadata.name,CIDR:spec.podCIDR'
NAME        CIDR
worker1     10.200.0.0/24
worker2     10.200.1.0/24
```
This doesn't appear to cause a problem but - if I wanted to preserve the podCIDR values as specified in each kubelet's `kubelet-config.yaml`, would that be possible? Is one way better than the other? What entity and setting is overriding the podCIDR in `kubelet-config.yaml`. I can't find the answer in any documentation I've been able to find so far.

Thanks

**Comment by aauren** [comment]
Hi there @aceeric.

Glad that you're trying out kube-router. In terms of Pod CIDR, this value is set on the k8s node object by the kube-controller-manager when `--allocate-node-cidrs` is set to `true`. If kube-router is setup to be responsible for pod networking, then it is expected that this value on the node object will match the CNI configuration in `/etc/cni/net.d/10-kuberouter.conf` or as otherwise specified via `--cni-conf-dir`.

To that end kube-router will update this file automatically upon starting by fetching the information for the node from the kube-apiserver. This essentially orchestrates the ipam CNI for the user using values from the kube-apiserver that were set by the kube-controller-manager. This information is peppered through the docs, but maybe not consolidated in any one place.

You can find more info in:
https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#requirements
https://github.com/cloudnativelabs/kube-router/blob/master/docs/how-it-works.md
https://github.com/cloudnativelabs/kube-router/blob/master/docs/generic.md

In terms of kubelet-config.yaml this is not something that kube-router does anything with. If you find this file changing on its own, it's possible that some other orchestration system is doing that for you like `kubeadm` or `kops`, however, this would not be a function of kube-router.

While we're happy to answer questions that come up, because this is a fairly large project, we ask that questions be asked in Slack so that it is easier to see bug/feature requests via the GitHub issues.
