### ISSUE TITLE
Support Ping for externalIP with DSR enabled

### ISSUE THREAD

**Issue by qingkunl** [cloudnativelabs/kube-router#1044]
I see this has been previously reported in https://github.com/cloudnativelabs/kube-router/issues/644.

Is that possible to support ping for externalIP when DSR is enabled?

We need this feature in our production environment.

Thanks.

**Comment by aauren** [comment]
Closing as it was already stated that this is not possible due to how DSR is implemented: https://github.com/cloudnativelabs/kube-router/issues/644#issuecomment-456452217

If you have more information on how this could be facilitated while retaining kube-router's DSR strategy feel free to comment and I'll consider reopening this issue.
