### ISSUE TITLE
host egress traffic blocked when default deny egress network policy applied with pods in hostNetwork 

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#1067]
**What happened?**
When [default deny egress](https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic) is applied in a namespace, and a host has pods in hostNetwork then traffic is blocked for host as well 

**What did you expect to happen?**
Host should be able to send the egress traffic. Network policy rule should only apply to the pods

**How can we reproduce the behavior you experienced?**

- deploy network policy https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic in a namespace
- deploy pods with hostNetwork in the same namespace
- check host is able to send outbound traffic

** System Information (please complete the following information):**
 this issue exists possibly before 1.0.0 release as well

**Comment by aauren** [comment]
Just to explain the situation with HostNetwork'd pods a bit more for posterity. Our decision to exclude HostNetwork pods comes from a variety of issues.

First, we want to adhere to upstream guidance as it pertains to the network environment and Kubernetes. While the concept of how Kubernetes Network plugins should integrate with HostNetwork pods isn't definitively laid out, we can derive some information via [The Kubernetes Network Model](https://kubernetes.io/docs/concepts/cluster-administration/networking/#the-kubernetes-network-model):
```
Kubernetes imposes the following fundamental requirements on any networking implementation (barring any intentional network segmentation policies):

    * pods on a node can communicate with all pods on all nodes without NAT
    * agents on a node (e.g. system daemons, kubelet) can communicate with all pods on that node
Note: For those platforms that support Pods running in the host network (e.g. Linux):

    * pods in the host network of a node can communicate with all pods on all nodes without NAT
```

While I think that this can be taken a number of ways, conversations in the SIG-NET team usually interpret this as that it should not be affected by Network Policy. This is exemplified by a member of SIG-NET in the following issue comment: https://github.com/kubernetes/kubernetes/issues/51891#issuecomment-347542541

Second, through this issue we tried to look into ways to allow kube-router to solve NetworkPolicy for HostNetwork'd pods and found no good options. The truth is, that HostNetwork pods look exactly like the host itself since it sits in the Host's network namespace. Given this we don't have a good way to identify and target the traffic that is coming/going to the pod as opposed to legitimate host traffic.

This was actually the problem that caused his issue to be raised. Without the work done in #1073 a user could unintentionally remove connectivity to nodes if they applied NetworkPolicy to a HostNetwork enabled pod. i.e. a rule like `Allow ingress on port 80` for a HostNetwork'd pod would cause kube-router to drop inbound packets to all other ports, as once NetworkPolicy is applied to a node, policy becomes whitelist only.

Third, we looked around at what other similar Network plugins do and we found that they also don't consider HostNetwork'd pods when applying Network Policy: https://github.com/projectcalico/calico/issues/4493#issuecomment-814272944

So for all of these reasons, we decided that we will no longer attempt to enforce NetworkPolicy on HostNetwork'd pods.
