### ISSUE TITLE
network_policy_controller.go generates incorrect iptables rules

### ISSUE THREAD

**Issue by v42net** [cloudnativelabs/kube-router#1076]
**What happened?**

[`network_policy_controller.go`](https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/netpol/network_policy_controller.go) generates KUBE-ROUTER-INPUT filter rules with a `-j RETURN` when accepting traffic. This results in a return to the INPUT filter rules and if the INPUT filter policy has been set to DROP, the traffic that should have been accepted is dropped.

**What did you expect to happen?**

[`network_policy_controller.go`](https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/netpol/network_policy_controller.go) should generate KUBE-ROUTER-INPUT filter rules with a `-j ACCEPT` when accepting traffic.

**How can we reproduce the behavior you experienced?**

1. Install a minimal Debian 10.9 system with curl and iptables (iptables-legacy), but no iptables rules configured. 
2. Install k3s server using the [Quick-Start Guide](https://rancher.com/docs/k3s/latest/en/quick-start/) and confirm it is operating correctly. As a reference for the correct situation use `iptables-save` to save the now active rules as generated by k3s. 
3. Remove k3s with `k3s-uninstall.sh` and reboot or re-install the system to be able to start with a clean slate.
4. Configure iptables rules to allow input from interface `lo`, protocol `icmp`, RELATED and ESTABLISHED traffic, and ssh traffic (tcp/22). Configure the default input and forward policies to drop traffic. The default output policy remains unchanged and accepts traffic. 
5. Configure additional iptables rules based on the *Networking* section of the [Installation Requirements](https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/), using the external IP address of the system as the source address (when installing a cluster these rules will be duplicated with the address of each cluster node as the source address).
6. Activate the configured iptables rules and install k3s server using the same procedure as before. Observe that k3s will *not* start correctly. As a reference for the failing situation use `iptables-save` to save the now active rules (the initial rules plus the k3s generated rules).

**System Information (please complete the following information):**

- Debian version 10.9
- Linux kube 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
- iptables v1.8.2 (legacy)
- k3s version v1.20.6+k3s1 (8d043282) which includes the kube-router network policy controller component
- go version go1.15.10
 
**Additional context**

- See [k3s issue #3258](https://github.com/k3s-io/k3s/issues/3258) for my initial bug report (including the iptables rules I used).
- In [k3s network_policy_controller.go](https://github.com/k3s-io/k3s/blob/master/pkg/agent/netpol/network_policy_controller.go) the issue is implemented at lines 317, 324, 332 and 341 (after commit `2705431`).
- In [kube-router network_policy_controller.go](https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/netpol/network_policy_controller.go) the issue is implemented at lines 347, 354, 362 and 371 (after commit `be01f31`).

**Comment by aauren** [comment]
@v42net Thanks for reporting.

I think that this is similar to https://github.com/cloudnativelabs/kube-router/issues/984#issuecomment-692331741 only with the INPUT table instead of the FORWARD table. Additionally, there is no out on this one by running kube-router with `--run-router` (which adds an unconditional ACCEPT after processing network policy chains).

You can see some history in that thread as well about why we chose to going with explicit `REJECT`s instead of `ACCEPT`s, although I'll admit that it makes less sense on the INPUT chain than it does on the FORWARD chain. All the same, in order to keep the iptables rules somewhat similar we'll probably add an ACCEPT after processing the policy chain if the packet has been approved by at least one policy.

@murali-reddy is already working on a fix for #984 as his next task, so we'll probably knock out both of these bugs at the same time for both `FORWARD`, `INPUT`, and `OUTPUT`. As a matter of fact, we had attempted to fix this several times in  #1009 and #1010, however both of those PR got closed in favor of #1039 which was missing this fix, so this issue was already on our radar a bit to fix soon.

**Comment by v42net** [comment]
@aauren Thanks for your response.

I checked #1002, #1009, #1010 and #1039 where this fix indeed went missing. I'll subscribe to #984 and #1039 and wait for the fix to become available. As soon as it is I will report it to the `k3s` project so they can update their version of `network_policy_controller.go`.

@murali-reddy I'm really impressed by the improvements provided by #1039 😃.

**Comment by aauren** [comment]
Closing as this should be fixed now that #1108 has been merged.

@v42net Would you be willing to try `kube-router` from master to see if this fixes the issue you saw? If not, you can wait until we release `1.3` later this week / next week. But it would be good to get some confirmation that this fixes what you saw. If it doesn't, I'll re-open, but we like to close early so that we don't end up with a stale issue backlog.
