### ISSUE TITLE
The BGP neighbor relationship cannot be established when config two peer-router

### ISSUE THREAD

**Issue by yuchunyun** [cloudnativelabs/kube-router#1190]
here are my running parameters
      - args:
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --bgp-graceful-restart=true
        - --advertise-external-ip=true
        - --service-external-ip-range=202.173.12.0/24
        - --service-external-ip-range=192.168.120.0/24
        - --cluster-asn=64611
        - --peer-router-ips=202.173.8.36,202.173.8.37
        - --peer-router-asns=64600,64600
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        - --v=5

image: docker.io/cloudnativelabs/kube-router
k8s version: v1.22.2

the two neighbors have the same BGP configuration, but a neighbor is always in the Active state

--- BGP Neighbors ---
Peer              AS     Up/Down State       |#Received  Accepted
192.168.110.11 64611 9d 22:45:00 Establ      |        1         1
192.168.110.12 64611 9d 22:44:52 Establ      |        1         1
192.168.110.13 64611 9d 22:44:21 Establ      |        1         1
192.168.110.14 64611 9d 22:44:54 Establ      |        1         1
192.168.110.15 64611 9d 22:44:08 Establ      |        1         1
192.168.110.16 64611 9d 22:44:39 Establ      |        1         1
192.168.110.17 64611 9d 22:44:28 Establ      |        1         1
202.173.8.36   64600 9d 22:38:44 Establ      |        0         0
202.173.8.37   64600       never Active      |        0         0

**Comment by aauren** [comment]
This seems like its unlikely to be a problem with kube-router since you've already demonstrated that kube-router peers with itself and one of your peers just fine. This seems a lot more likely to be a BGP configuration issues on your second peer.

Can you provide logs from the peer and kube-router when it tries to peer that evidence what the problem might be?

If you don't see anything in the kube-router logs you should be able to get more information by putting gobgp (what kube-router uses to work with BGP) into debug logging as described here: https://github.com/cloudnativelabs/kube-router/issues/363#issuecomment-895079824

**Comment by yuchunyun** [comment]
Resolved. 
The reason is that my two upper-layer routers are in active/standby relationship, and the TTL from the node to the standby router is 3. Therefore, I must set the peer-router-multihop-TTL parameter.
Thx

**Comment by aauren** [comment]
Thanks for reporting back, it's super helpful to other users that come along with similar errors in the future. Glad that you got it sorted!
