### ISSUE TITLE
no iptable rules is generated with k3s and flannel by setting network policy

### ISSUE THREAD

**Issue by vanloswang** [cloudnativelabs/kube-router#1191]
**What happened?**
iptable rules is not generated with k3s and flannel by setting network policy.

**What did you expect to happen?**
iptable rules is generated with k3s and flannel by setting network policy.

**How can we reproduce the behavior you experienced?**
1. install k3s all-in-one cluster, and deploy a ngnix web app.
2. deploy kube-router as firewall
`
# ./kube-router --kubeconfig=/etc/rancher/k3s/k3s.yaml --iptables-sync-period=1s --run-firewall=true --run-router=false --run-service-proxy=false
`
3. create network policy
`
# vim service-access-control.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: service-access-control
spec:
  podSelector:
    matchLabels:
      app: web
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.1.0/24
        except:
        - 192.168.1.10/32
    - namespaceSelector:
        matchLabels:
          project: default
    ports:
    - protocol: TCP
      port: 20436
`
# kubectl create -f service-access-control.yaml
4. wait a second,  check the iptable rules and there is not generated rule. iptable rules are generated by calico canal with the same network policy.
`
iptables -nvL | grep 192
`

** System Information (please complete the following information):**
 - Kube-Router Version :[v1.3.2]
 - Kube-Router Parameters: [--kubeconfig=/etc/rancher/k3s/k3s.yaml --iptables-sync-period=1s --run-firewall=true --run-router=false --run-service-proxy=false]
 - Kubernetes Version : [v1.21.6+k3s1]
 - Kubernetes Deployment Type: [k3s]
 - Kube-Router Deployment Type: [System Service]
 - Cluster Size: [1 Nodes]

**Comment by aauren** [comment]
This will have to be some sort of user configuration issue, for this to be an actual bug, kube-router's firewall capability would have to be broken for all users for weeks. I can assure you that isn't the case.

Some likely candidates for you to check:
* Are you sure that your network policy pod selector actually matches a pod with that label in whatever your default namespace is in your k8s configuration? It's almost always better to specify a namespace on your k8s objects rather than letting it default.
* Have you looked at kube-router's logs? Are there any errors about permissions or some such? Are there any other errors at all?
* Whenever you sort out your config you'll want to also change the firewall sync time that you set. 1 second is way too low and will likely cause poor system performance for you as kube-router will be constantly executing full syncs.

Hopefully this helps give you some things to check so that you can take the next steps.
