### ISSUE TITLE
Update v1.2.3 to address security vulnerabilities 

### ISSUE THREAD

**Issue by ssstopalle** [cloudnativelabs/kube-router#1215]
**Is your feature request related to a problem? Please describe.**
We use kube-router v1.2.3 and recent container scans show vulnerabilities in the following packages:

LIBRARY : github.com/containerd/containerd                                                 
INSTALLED VERSION: v1.4.4                                      
FIX VERSION:  v1.4.11, v1.5.7
VULNERABILITY ID:  CVE-2021-41103
SEVERITY: HIGH

LIBRARY : golang.org/x/crypto                                                  
INSTALLED VERSION: v0.0.0-20201002170205-7f63de1d35b0                                    
FIX VERSION: v0.0.0-20201216223049-8b5274cf687f
VULNERABILITY ID :  CVE-2020-29652
SEVERITY: HIGH

Requesting an update to these packages for the 1.2.3 line of release

**Describe the solution you'd like**
An update to these packages would help resolve the security vulnerabilities in these packages

**Describe alternatives you've considered**

**Additional context**

**Comment by aauren** [comment]
At this point there is no plan to backport the containerd fix to 1.2.3. kube-router-1.2.3 is more than 6 months old at this point and there were some complex dependencies between containerd and protobuf and gobgp that we have finally resolved on the main branch that would be difficult to bring backwards.

Additionally, there is no impact to kube-router from the above vulnerability. While the binary contains an affected containerd library version, the CVE itself is for containerd running containers which is not how we use containerd inside kube-router. In fact, the only reason that it is in the dependency graph for kube-router at all is because we import `github.com/containernetworking/plugins` so that we can parse the CNI configuration, and `github.com/containernetworking/plugins` depends on `github.com/Microsoft/hcsshim` for some random Windows compatibility and hcsshim in turn depends on containerd.

As soon as we resolve a few recently submitted issues I plan to release kube-router 1.4.0 and at that point we'll have an official release of kube-router that no longer contains the affected containerd library. Until then, if you need to run a version of kube-router that doesn't contain the affected containerd library for compliance reasons or some such I would suggest that you run kube-router from kube-router-git or compile it from the main branch.
