### ISSUE TITLE
Error exporting routes to IPv4 peer when running dual stack environment

### ISSUE THREAD

**Issue by xaque208** [cloudnativelabs/kube-router#1233]
**What happened?**

Trying to use kube-router to export service routes to the rest of my BGP network for easy of management.  I'm using this as my starting point: https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/generic-kuberouter-only-advertise-routes.yaml

I'm running on K3s in a dual stack configuration, but I understand that ipv6 isn't supported.  IPv4 routes exported is a first step.

I see in the logs:

```
Failed to add `servicevipsdefinedset` defined set: multiple families
```

**What did you expect to happen?**
I thought since the peer came up, that the service routes etc would be exported to my peer, but I see no such routes arrive.

**How can we reproduce the behavior you experienced?**
1. Run a dual stack cluster
2. Have a mix of ipv4 services and ipv6 services
3. Configure BGP for the environment
3. Apply the above manifest
4. Observe the lgos

**Screenshots / Architecture Diagrams / Network Topologies **

A single peer.

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): `v1.4.0`
 - Kube-Router Parameters: 
 ```
        args:
        - "--run-router=true"
        - "--run-firewall=false"
        - "--run-service-proxy=false"
        - "--bgp-graceful-restart=true"
        - "--enable-cni=false"
        - "--enable-ibgp=false"
        - "--enable-overlay=false"
        - "--peer-router-ips=172.16.15.1"
        - "--peer-router-asns=xxx"
        - "--cluster-asn=yyy"
        - "--advertise-cluster-ip=true"
        - "--advertise-external-ip=true"
        - "--advertise-loadbalancer-ip=true"
        - "--metrics-port=9011"
        - "--service-cluster-ip-range=10.43.0.0/16" <-- this was added to try and fix the issue
````
 
 - Kubernetes Version (`kubectl version`) : [e.g. 1.18.3]
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"archive", BuildDate:"2022-01-14T09:18:54Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+k3s1", GitCommit:"61a2aab25eeb97c26fa3f2b177e4355a7654c991", GitTreeState:"clean", BuildDate:"2021-11-04T00:24:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
 - Cloud Type: on premise with `k3s`
 - Kubernetes Deployment Type: `kubectl apply`
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 3 nods

** Logs, other output, metrics **

```
I0114 21:27:43.573048       1 version.go:21] Running /usr/local/bin/kube-router version v1.4.0, built on 2022-01-05T17:01:42+0000, go1.17.5
I0114 21:27:43.677214       1 metrics_controller.go:164] Starting metrics controller
I0114 21:27:43.697664       1 network_routes_controller.go:1298] Could not find annotation `kube-router.io/bgp-local-addresses` on node object so BGP will listen on node IP: 172.16.15.22 address.
I0114 21:27:43.771401       1 network_routes_controller.go:242] Setting MTU of kube-bridge interface to: 1500
E0114 21:27:43.772251       1 network_routes_controller.go:253] Failed to enable netfilter for bridge. Network policies and service proxy may not work: exit status 1
I0114 21:27:43.772395       1 network_routes_controller.go:273] Starting network route controller
time="2022-01-14T21:27:43Z" level=info msg="Add a peer configuration for:172.16.15.1" Topic=Peer
E0114 21:27:43.830593       1 bgp_policies.go:33] Failed to add `servicevipsdefinedset` defined set: multiple families
E0114 21:27:43.830694       1 network_routes_controller.go:346] Error adding BGP policies: Failed to add policy: not found prefix set servicevipsdefinedset
E0114 21:27:43.830719       1 network_routes_controller.go:356] Error during periodic sync in network routing controller. Error: Failed to add policy: not found prefix set servicevipsdefinedset
E0114 21:27:43.830735       1 network_routes_controller.go:357] Skipping sending heartbeat from network routing controller as periodic sync failed.
time="2022-01-14T21:27:50Z" level=info msg="Peer Up" Key=172.16.15.1 State=BGP_FSM_OPENCONFIRM Topic=Peer
```

**Additional context**
I'm still learning how to get traffic into my cluster still.  BGP seems like the right step, since it has been deployed in my environment for a long time, and has the fewest dependencies.  `kube-proxy` is also running in this cluster since I don't know much of what I'm doing yet, but the arguments to `kube-router` I believe are compatible with an existing `kube-proxy`.

**Comment by aauren** [comment]
The error that you received occurs because you have defined either a LoadBalancer type service or an External IP that is an IPv6 address. When kube-router is creating its BGP policies, it finds all of the VIPs currently defined in Kubernetes and then attempts to add them to some policies. The way that we currently use GoBGP, it will not allow both IPv4 and IPv6 addresses to coexist within the same policy so you get the error above. At this point the presence of any IPv6 service vips will not work with kube-router: https://github.com/cloudnativelabs/kube-router/blob/master/docs/ipv6.md

There were some plans a few years back to implement support, but this has not happened and I'm not aware of any push for this to happen any time soon as none of the current maintainers of the project have an IPv6 use-case and its a considerable amount of work for an external contributor. At this point, if you must have a mixed environment I would not recommend using kube-router on your nodes.

**Comment by xaque208** [comment]
Thank you for the information.  Is this to say then also, that if I moved all of my services to ipv6, then `kube-router` would be able to create the policy?

**Comment by aauren** [comment]
It might move you past this problem, but I would suspect that you would hit another problem in the kube-router code base related to IPv6. You'd have to test it, but keep in mind that you would be in uncharted waters. kube-router was not created with IPv6 in mind and the code makes ipv4 assumptions multiple places. In order to get use out of kube-router with IPv6 you would likely need to be very familiar with Go programming and be willing to resolve multiple issues as you encountered them.
