### ISSUE TITLE
Kube-router only update cni config when --run-router=true

### ISSUE THREAD

**Issue by vladimirtiukhtin** [cloudnativelabs/kube-router#1449]
My cloud provider handles routing, so I don't need BGP, but I need cni config to be populated for containerd to function properly

**Comment by aauren** [comment]
Sorry, but this isn't possible. If your cloud provider is handing the routing, then they should be providing you with the CNI configuration as well. kube-router generates the CNI based upon what it knows of your pod network because when you run it with `--run-router=true` it is maintaining that piece of your Kubernetes cluster. If it is not handling the routing for you, then it does not know what your pod network looks like and therefore cannot generate a CNI for you.
