### ISSUE TITLE
Default ACCEPT rule with network policy

### ISSUE THREAD

**Issue by rbrtbnfgl** [cloudnativelabs/kube-router#1453]
**What happened?**
I don't if it is the expected behaviour when configured the network policy all the network traffic between the pods is accepted by default on the FORWARD chain (https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/netpol/network_policy_controller.go#L424). In case also kube-proxy is deployed the forward chain should be as follow:
```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    7   628 KUBE-ROUTER-FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-router netpol */
    0     0 KUBE-PROXY-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes load balancer firewall */
    0     0 KUBE-FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding rules */
    0     0 KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes service portals */
    0     0 KUBE-EXTERNAL-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes externally-visible service portals */
    0     0 FLANNEL-FWD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* flanneld forward */
```
In case of packets generated by the pods the traffic will be accepted by the first rule and it will not matching the other kube-proxy rules and could lead to this https://github.com/k3s-io/k3s/issues/6691

**What did you expect to happen?**
Will it be better to set as RETURN?

**How can we reproduce the behavior you experienced?**
1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Screenshots / Architecture Diagrams / Network Topologies **
If applicable, add those here to help explain your problem.

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): [e.g. 1.0.1]
 - Kube-Router Parameters: [e.g. --run-router --run-service-proxy --enable-overlay --overlay-type=full etc.]
 - Kubernetes Version (`kubectl version`) : [e.g. 1.18.3]
 - Cloud Type: [e.g. AWS, GCP, Azure, on premise]
 - Kubernetes Deployment Type: [e.g. EKS, GKE, Kops, Kubeadm, etc.]
 - Kube-Router Deployment Type: [e.g. DaemonSet, System Service]
 - Cluster Size: [e.g. 200 Nodes]

** Logs, other output, metrics **
Please provide logs, other kind of output or observed metrics here.

**Additional context**
This setup is done with kube-router embedded within K3s.

**Comment by aauren** [comment]
This seems like a reasonable assumption, however, it is a large change for users from the default which may bring unintended side-effects. I'm willing to give this a shot as part of the 2.0.0 release candidate and see if it causes problems for any testers.

As it stands how, if kube-router is run with `--run-router=true` then it should accept the traffic at the end of the FORWARD table anyway (assuming something like kube-proxy or some such doesn't produce a final action in between). So that use-case should already be fine. For folks that run it in `--run-firewall=true` without the `--run-router` it may cause some issues if they aren't will to or can't for whatever reason, either add a global `ACCEPT` policy on the `FORWARD` table or orchestrate a rule that would allow it.

However, I can't see another way to allow `kube-proxy` to be authoritative over service traffic (like the `REJECT` that it is trying to do here) without changing our default policy to `RETURN`. Keep in mind, that kube-router still does process `ACCEPT` on certain actions like `ESTABLISHED` or `RELATED` connections. I think it would be good to keep that policy the way that it is for performance reasons, so that bulk traffic still exits iptables early without having to traverse potentially unrelated rules.

Anyway, we're already making some other breaking changes for the v2.0.0 release so we'll give this a shot, but reserve the right to roll it back if it causes too much disruption.

**Comment by aauren** [comment]
It looks like I spoke too soon. After writing this, I felt like I remembered this coming up in the past. After a bit of digging through the git and github history, I found the following PR where we had to change our stance from RETURN to ACCEPT here because of the number of common use-cases that RETURN invalidated: https://github.com/cloudnativelabs/kube-router/pull/1108

If you trace that back you get to these two issues:
* https://github.com/cloudnativelabs/kube-router/issues/984
* https://github.com/cloudnativelabs/kube-router/issues/1076

Two may not seem like a lot, but it was only a small representation of the feedback that we got from users in slack and other places. In the past we've gone back and forth on this. In the original kube-router we set it to `ACCEPT`. Then after feedback from users like yourself and others we decided that `RETURN` was a better security posture and allowed other rules to be processed (I still think that this may be the better posture RE my comment above where I still default to this position when I don't have the history in front of me). However, after just a single release of it being set this way, we invalidated so many user's use-cases that we went back to `ACCEPT` with that PR.

I think we're going to leave it as `ACCEPT` for now. Luckily it's a single line patch, so it shouldn't be that hard for k3s to carry that one forward. If at some point in the future that changes, or becomes more difficult we could probably open up the conversation again and look at either exposing a CLI option, or since I believe that you're using kube-router as a Go library, maybe just a variable that can be set in the `NetworkPolicyController` struct.
