### ISSUE TITLE
Wrong source IP

### ISSUE THREAD

**Issue by vladimirtiukhtin** [cloudnativelabs/kube-router#1460]
**What happened?**
My nodes have two interfaces: internet facing with a default gateway and private network facing without a default gateway. When node starts everything works as expected. I can reach a pod by using its virtual IP from both a node and another pod. Now after some time I can no longer do it from a node because source IP has been changed to one assigned to internet facing link. ip route get still shows the correct IP, but in fact, source is different

**What did you expect to happen?**
I expected it to work

**How can we reproduce the behavior you experienced?**
I don't really know as it happens only after some time

**Screenshots / Architecture Diagrams / Network Topologies **
If applicable, add those here to help explain your problem.

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): [e.g. 1.0.1]
Running kube-router version 1.5.3, built on 2022-11-20T17:55:01Z, go1.19.2
 - Kube-Router Parameters: [e.g. --run-router --run-service-proxy --enable-overlay --overlay-type=full etc.]
--kubeconfig=/var/lib/kube-router/kubeconfig --run-router=true --run-firewall=true --run-service-proxy=true --enable-overlay=false
 - Kubernetes Version (`kubectl version`) : [e.g. 1.18.3]
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:22Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
 - Cloud Type: [e.g. AWS, GCP, Azure, on premise]
Hetzner

** Logs, other output, metrics **
The only interesting message is
```
o:195] Failed to replace route to service VIP 2a01:4f8:c011:b17::1 configured on kube-dummy-if. Error: exit status 1, Output: Error: inet6 address is expected rather than "10.103.0.4".
```

**Comment by vladimirtiukhtin** [comment]
I found below entry in my iptables
```
Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
88949 5341K KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */
    4   240 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set kube-router-pod-subnets src ! match-set kube-router-pod-subnets dst ! match-set kube-router-node-ips dst random-fully
   14   784 SNAT       all  --  *      *      !10.0.13.0/24        !10.0.13.0/24         vdir ORIGINAL vmethod MASQ /*  */ to:167.235.70.254 random-fully
    0     0 SNAT       all  --  *      *      !10.0.13.0/24        !10.0.13.0/24         vdir ORIGINAL vmethod MASQ /*  */ to:10.103.0.4 random-fully
```
Why external interface is above internal? After clearing and restarting kube-router everything starts work as expected and iptables changes to original state
```
Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
89065 5348K KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */
    0     0 SNAT       all  --  *      *      !10.0.13.0/24        !10.0.13.0/24         vdir ORIGINAL vmethod MASQ /*  */ to:10.103.0.4 random-fully
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set kube-router-pod-subnets src ! match-set kube-router-pod-subnets dst ! match-set kube-router-node-ips dst random-fully
```

**Comment by aauren** [comment]
Hmm... I've definitely not seen this before.

What I am able to tell you is the following:

* That IP address is only ever written to when kube-router is first starting and it first instantiates the NetworkServiceController struct: https://github.com/cloudnativelabs/kube-router/blob/1d1ff0599a43a2c4154a6c224c52fba87394444f/pkg/controllers/proxy/network_services_controller.go#L2348
* That means that in order for that to change, kube-router would have had to have been restarted, which isn't impossible if it were to be upgraded, or it failed a health-check, the node was rebooted, etc. but it certainly doesn't happen all the time. Maybe that's why you only see it sometimes happen this way?
* The way that it gets that address is from the node definition in Kubernetes. It looks at the node's `status.addresses` array and chooses the first `type: InternalIP` that it sees, and if it doesn't see one of that type, then it will choose the first `type: ExternalIP`
* Normally, this address structure is very stable, and is set by either the Kubelet or your Cloud Provider

I would guess that Hetzner or whatever you're using to orchestrate your Kubernetes cluster is occasionally mixing this structure on the node. I can say with confidence, that as long as your internal IP address, in this case `10.103.0.4`, is consistently typed with `InternalIP` and your external IP is consistently typed with `ExternalIP` that you would not see this issue.

I would follow up with either your cloud provider or your Kubernetes orchestrator to see if you can get these to be labeled and arranged consistently. Maybe do a long-term watch on your node object to see what might be modifying it and when? You could also turn on audit logging in Kubernetes for node events as well to see what is changing this.

As an aside, the log message that you posted shows that you're running in a Kubernetes cluster with dual-stack enabled. kube-router is just barely beginning to support dual stack as of our v2.0.0 release candidate line and the `--run-service-proxy` option is still the last controller that we have not yet converted. Keep in mind that your mileage may vary widely if you use IPv6 in your cluster right now with kube-router, and I would highly recommend upgrading to one of the v2.0.0 release candidates as at least `--run-firewall` and `--run-router` are fixed to work with a dual-stack cluster.

**Comment by vladimirtiukhtin** [comment]
Thanks @aauren I could confirm that if kube-router starts too early, before cloud controller updates node object with correct external and internal IPs, it chooses external IP which breaks installation. Now I only need to find out how to delay kube-router start time. Is there a flag to wait until node is in initialized stage?
