### ISSUE TITLE
Getting RST on long-lived connections

### ISSUE THREAD

**Issue by vladimirtiukhtin** [cloudnativelabs/kube-router#1577]
**What happened?**
I don't know exactly but from time to time my apps receive RST from the kernel they are running on. It looks very much like this https://unix.stackexchange.com/questions/572276/l4-balancing-using-ipvs-drop-rst-packets-failover but there is no IP switching or anything

App does syn/ack, then works.... time passes here..... app sends `[P.]` and gets RST from kernel immediately. I have a feeling that some syncing/re-syncing mechanism in kube-router flashes state table (does ipvs have state table??)

**What did you expect to happen?**
Nothing like that, just a working socket

**Screenshots / Architecture Diagrams / Network Topologies **
![Screenshot from 2023-11-28 17-39-33](https://github.com/cloudnativelabs/kube-router/assets/15124334/f864ada9-2321-4828-a140-bb9476fc2b4c)

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): 1.6.0

**Comment by vladimirtiukhtin** [comment]
`sysctl net.ipv4.vs.sloppy_tcp=1` seems to resolve the problem, but how will it behave with IPv6?

**Comment by aauren** [comment]
Can you please add your reproduction scenario to this issue? There isn't really enough information in this in order for me to do anything with this.

It may be that #911 would resolve the issue that you're seeing, but without more details and concrete steps to reproduce this, I can't be sure.

In general, since we had two issues related to timeout flexibility, we should probably expose the option. Given that, I'll re-open #911 and submit a PR to allow it to be configured. But I can't be sure that, that will resolve what you're experiencing without more information.

**Comment by aauren** [comment]
If you want to try adjusting IPVS timeouts you can try doing so via: https://hub.docker.com/layers/cloudnativelabs/kube-router-git/PR-1590/images/sha256-4912ca11f4dc6fa41a73c9549e8191f744cb30e170332bd90f0e3e2d563eebbf?context=explore

See #1590 for more information on the exposed options.
