### ISSUE TITLE
kube-router should cleanup rules it does not handle anymore in its chains

### ISSUE THREAD

**Issue by TPXP** [cloudnativelabs/kube-router#1675]
**What happened?**
Hello, we're happily using kube-router to handle network policies on our kubernetes cluster (`--run-router=false --run-firewall=true --run-service-proxy=false`). Recently, we performed a bunch of kube-router upgrades to get the latest version:
* Initial version: v1.5.3
* 1st upgrade: v2.0.1
* 2nd upgrade: v2.2.1

Recently, we noticed some packet drops impacting performance of our applications. Our investigations led us to look at iptables on our server. These look mostly OK, except for the `KUBE-ROUTER-INPUT` chain in the `ip filter` table. Indeed, on some of our machines, it that some rules are repeated:
```
# iptables-save
-A KUBE-ROUTER-INPUT -d 10.96.0.0/12 -m comment --comment "allow traffic to cluster IP - 4H2UH6XHRCCZXCYQ" -j RETURN
-A KUBE-ROUTER-INPUT -d 10.96.0.0/12 -m comment --comment "allow traffic to primary/secondary cluster IP range - BVHX2PIHDXXEO43X" -j RETURN
-A KUBE-ROUTER-INPUT -d 10.96.0.0/12 -m comment --comment "allow traffic to primary/secondary cluster IP range - BVHX2PIHDXXEO43X" -j RETURN
-A KUBE-ROUTER-INPUT -d 10.96.0.0/12 -m comment --comment "allow traffic to cluster IP - 4H2UH6XHRCCZXCYQ" -j RETURN
-A KUBE-ROUTER-INPUT -d 10.96.0.0/12 -m comment --comment "allow traffic to primary/secondary cluster IP range - BVHX2PIHDXXEO43X" -j RETURN
-A KUBE-ROUTER-INPUT -d 10.96.0.0/12 -m comment --comment "allow traffic to cluster IP - 4H2UH6XHRCCZXCYQ" -j RETURN
[... 2 lines above repeated around 10 times ...]
```

It looks like "allow traffic to cluster IP" rules do not exist anymore in the source code (they were dropped during the v2.0 rewrite it seems). Sure, we could reboot our server to clear these rules but this would cause some downtime. We've also considered running `kube-router --cleanup-config` but this clears all rules, causing some network downtime until kube-router syncs rules (which happens every 5mins it seems).

We're also puzzled by rules being duplicated, but the issue is more severe on another set of rules so I'll open a separate issue to discuss this.

**What did you expect to happen?**
I think kube-router should remove rules it does not handle from its top-level chains (like "KUBE-ROUTER-INPUT"). Another possibility could be to match rules we know were created by older versions like "allow traffic to cluster IP".

I think the `KUBE-ROUTER-INPUT` states clearly that this chain is handled by kube-router so I don't think we should worry about breaking other tools - thus dropping rules we don't need in this chain seems acceptable to me.

**How can we reproduce the behavior you experienced?**
Can't say for sure, here's my guess:
1. Run a cluster with a cluster IP service
2. Deploy kube-router v1.5.3 as a daemonset 
3. Upgrade to kube-router v2.0.1, let it run for a few syncs (something like an hour for it to sync 12 times?)
4. Upgrade to kube-router v2.1.2, let it run for a few syncs (something like an hour for it to sync 12 times?)
5. Look at iptables on a cluster node. In doubt, use the iptables binary provided by kube-router: `kubectl exec kube-router -- iptables-save`

**Screenshots / Architecture Diagrams / Network Topologies**
N/A

**System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): 2.1.2
 - Kube-Router Parameters: `--run-router=false --run-firewall=true --run-service-proxy=false`
 - Kubernetes Version (`kubectl version`) : v1.29.1
 - Cloud Type: bare metal
 - Kubernetes Deployment Type: Bare metal. Our servers run Ubuntu 22.04 LTS
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: about 25 nodes

**Logs, other output, metrics**
I couldn't find anything suspicious in kube-router logs. Raising the logging level could help, let me know if you need that!

**Additional context**
We've been using kube-router for a few years and it has served us well, thanks for maintaining it! <3

**Comment by aauren** [comment]
Hey there!

We appreciate the loyalty to kube-router, its definitely a project that we're passionate about as well. I'm glad that you've been using it and enjoying it.

I think in the particular case, it's good to know that this is a problem and to have this as a reported issue since we hadn't seen this issue before.

However, at this point I think that we're unlikely to fix it for several reasons:
* exec'ing out to iptables / ipset is the most costly operation that kube-router has right now, and each additional one causes total sync time to verge into the unreasonable
* The logic that exists right now checks for this rule each time a NetworkPolicy sync is requested, so if we wanted this to be a one-time thing, we'd have to right a brand new logic structure for this
* In the past we've maintained backwards compatibility fixing of old iptables rules, and its difficult to know when these rules can be retired and causes pain for refactoring logic and the like for single point-in-time upgrades
* v2.0.0 is a brand new major version and as such there is no expectation from the project that backwards compatibility will be retained
* Because of the above (major version bump), the project has already recommended that user's issue a rolling reboot of their nodes on upgrade from v1.X to v2.X of kube-router in the release notes:

>At this point, the project recommends doing a rolling-reboot of nodes after the application (or as part of) of this release to ensure that unused tunnels are properly cleaned up and don't have a negative impact on traffic flows.

Granted, in that paragraph it was specifically talking about the negative impact of created tunnels, but I would say this is just another example of the break in functionality.

I appreciate the issue all the same, as it will help other users who maybe see similar problems in their clusters. However, at this point the project won't be fixing this one. While rolling reboots are not something to be taken lightly, this upgrade is the only time that kube-router has required this in its past and I think that it's necessary here to keep the code paths simpler and more efficient.

**Comment by TPXP** [comment]
Thanks a lot for your detailed reply. As long as we reboot our nodes when upgrading from v1 to v2 this issue is indeed fixed. That seems like an acceptable workaround, we'll go for that instead. 👍
