### ISSUE TITLE
Service traffic being dropped when NetworkPolicy is present

### ISSUE THREAD

**Issue by k6av** [cloudnativelabs/kube-router#1701]
## What happened?

When using a network policy, traffic that should be allowed is silently dropped without a reject message; TCP connections time out.

## What did you expect to happen?

Network traffic can reach the service and underlying pod normally.

## How can we reproduce the behavior you experienced?

1. Create a pod that exposes e.g. port 8000 with label `app.kubernetes.io/name=myserver`
2. Create a (non-headless) service for the server pod (allocated clusterIP is, say, `fdcd:5f23:4ab4:11::abcd`).
3. Create a `NetworkPolicy` with type `Ingress`, that allows traffic on port 8000 to pods with `app.kubernetes.io/name=myserver` from pods with `app.kubernetes.io/name=myclient`.
4. Create a pod with label `app.kubernetes.io/name=myclient`.
5. Attempt to dial the service on port 8000, e.g. `curl -v http://[fdcd:5f23:4ab4:11::abcd]:8000`.

## System Information
 - Kube-Router Version (`kube-router --version`): master branch (as of commit e8962dd)
 - Kube-Router Parameters: --enable-cni=true --run-router=true --run-firewall=true --run-service-proxy=true --run-loadbalancer=true --bgp-graceful-restart=true --kubeconfig=/var/lib/kube-router/kubeconfig --enable-ipv4=false --enable-ipv6=true --router-id=generate --service-cluster-ip-range=fdcd:5f23:4ab4:11::/112 --loadbalancer-ip-range=fdcd:5f23:4ab4:12::/112
 - Kubernetes Version (`kubectl version`) : v1.28.10
 - Cloud Type: on premise
 - Kubernetes Deployment Type: custom
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: single node

## Additional context
The issue occurs/disappears under very strange conditions, so far I've discovered:

- If steps 2 and 3 are reversed such that the policy is created *after* the client pod, the issue does not occur.

- The issue occurs *only* when a NetworkPolicy exists and allows traffic. With no NetworkPolicy at all the service works normally. When the traffic is not allowed by the NetworkPolicy, a reject message (`Connection refused`) is received (as expected).

- If a client pod dials the IP of a service's endpoint (pod IP) directly, then dialing the service IP works for that client pod from there on. The issue still occurs in all other pods.

**Comment by aauren** [comment]
Thanks for filing this bug! This was a tricky one to track down and it took me a few days to get to the bottom of it, but eventually, I think that I got it figured out.

Basically, ICMPv6 neighbor discovery was failing to be allowed once networkpolicy was applied. If a connection had been established before policy was applied, the discovery would have already been successful and subsequent communication would succeed after the policy was applied.

However, if, as your steps showed, the policy was applied before any communication had been initiated, the ICMPv6 advertisement and solicitation messages would be dropped.

This should be fixed in #1710, if you could, it would be awesome if you could test the container that comes out of the actions pipeline to ensure that it fixed the error for you as well.

**Comment by k6av** [comment]
Thanks so much for the fix! I have not yet tested the PR, but if any issues arise I'll reopen the issue. Thanks.
