### ISSUE TITLE
Pod traffic to remote nodeIP should not use the tunnel interface

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#172]
With default settings and nodes in different subnets, ipip tunneling is used between nodes and pod CIDR egress is masqueraded. This works for most scenarios however a special case is when a pod accesses an external facing address of another node. I believe this is where problems start (communication hangs after reaching the target node).

### Example
Node A (controller-01) has
- External IP: 147.75.95.177/31
- Pod CIDR: 10.2.0.0/24

Node B (worker-01)has
- External IP: 147.75.95.175/31
- Pod CIDR: 10.2.1.0/24

I start a pod on Node B, and try to ping Node A's external interface:
```
$ k run alpine --rm -ti --image=alpine ping 147.75.95.177
# hangs
```

I see pings coming in to Node A on the tunnel interface, but no reply:
```
core@controller-01 ~ $ sudo tcpdump -vnni tun-1477595175 icmp 
dropped privs to tcpdump
tcpdump: listening on tun-1477595175, link-type RAW (Raw IP), capture size 262144 bytes
13:07:42.696948 IP (tos 0x0, ttl 63, id 39743, offset 0, flags [DF], proto ICMP (1), length 84)
    147.75.95.175 > 147.75.95.177: ICMP echo request, id 2048, seq 91, length 64
13:07:43.697104 IP (tos 0x0, ttl 63, id 40620, offset 0, flags [DF], proto ICMP (1), length 84)
    147.75.95.175 > 147.75.95.177: ICMP echo request, id 2048, seq 92, length 64
13:07:44.697249 IP (tos 0x0, ttl 63, id 41481, offset 0, flags [DF], proto ICMP (1), length 84)
    147.75.95.175 > 147.75.95.177: ICMP echo request, id 2048, seq 93, length 64
```

The source IP was masqueraded from the Pod IP to Node B's external IP: `147.75.95.175 > 147.75.95.177`

Now, on Node B, if I turn off masquerading just for traffic going to Node A, source Pod IP is retained, still going over the tunnel, and replies are received successfully.

On Node B:
```
core@worker-01 ~ $ sudo iptables -t nat -I POSTROUTING -m set --match-set kube-router-pod-subnets src -d 147.75.95.177 -j RETURN
```

On Node A:
```
core@controller-01 ~ $ sudo tcpdump -vnni tun-1477595175 icmp
dropped privs to tcpdump
tcpdump: listening on tun-1477595175, link-type RAW (Raw IP), capture size 262144 bytes
13:14:07.183842 IP (tos 0x0, ttl 63, id 63653, offset 0, flags [DF], proto ICMP (1), length 84)
    10.2.1.4 > 147.75.95.177: ICMP echo request, id 2048, seq 8, length 64
13:14:07.183885 IP (tos 0x0, ttl 64, id 38404, offset 0, flags [none], proto ICMP (1), length 84)
    147.75.95.177 > 10.2.1.4: ICMP echo reply, id 2048, seq 8, length 64
```

**Comment by bzub** [comment]
We had to add policy based routing to ensure tunnel traffic returns over the tunnel and not some other interface. The rule only acts on traffic from pod CIDR addresses, not from other node's external facing addresses. So I believe we either need to prevent masquerading for pod to nodeIP traffic, or prevent that traffic from going over the tunnel.

**Comment by murali-reddy** [comment]
ok i get the root casue, current PBR implemented applied for the case where `node A` accessing `pod B` on `node B` (case of proxying to service endpoint). So return traffic from `pod B` goes through the same tunnel interface on which it arrived. Problem we are seeing is the converse scenario. `pod B` accessing `node A`. On `node B` we dont need any policies to be applied, but due to the way current implementation of PBR, traffic goes through the tunnel which is wrong. on `node A` traffic arrives on tunnel interface and leaves on the physical interface, which `rp_filter` to drop the packets. So clean fix is it apply policy based rules only to the return traffic from the pods.

**Comment by murali-reddy** [comment]
I thought about a bit. So current policy based routes are setup as below.

```
ip rule add from nodes-pod-cidr table kube-router
```
So traffic from pod is always looked through the `kube-router` table. In the table for each node in different subnet as current node, we add a route as below

```
ip route add remote-node-node-ip dev tunnelName table kube-router
```

So this covers both the cases of pod->node and node->pod working properly. Lets assume `node A` and `node B` are in different subnets.

- when `pod A` running on `node A` accessing `node B`, traffic from `pod A` goes through the tunnel interface due PBR setup on `node A`. On `node B` traffic arrives on tunnel interface. Return traffic leave on tunnel interface as well, as route to `pod A` is setup to go through tunnel inteface. So no issue with `rp_filter` and end to end path works as expected.
- when `node A` access `pod B` running on `node B`, traffic from `node A` goes through tunnel interface. On `node B` traffic arrives on tunnel interfacce, and sent to the pod. Return traffic from `pod B` is looked through PBR, and sent over the tunnel interface to `node A`

so both the cased traffic arrive and leave on same interface, so `rp_filter` wont drop any packets.

However #173 need to be fixed, so that traffic from pod to node does not get NATed, otherwise traffic arrives and leaves on different interfaces on `node B`
