### ISSUE TITLE
Can KubeRouter component on a certain Node only generate the KUBE-NWPLCY-xxx Chain for the NetworkPolicy associated with the Pod on this Node?

### ISSUE THREAD

**Issue by woooniuzhang** [cloudnativelabs/kube-router#1751]
## What happened?
I found that the KubeRouter will create a related PolicyChain KUBE-NWPLCY-xxx for every NetworkPolicy of the cluster on every K8S Node.  When the K8S cluster has a large number of NetworkPolicies, it may cause too many IPtables Rules on each node, thus affecting performance. 

## What did you expect to happen?
I hope that the KubeRouter component on a certain Node  only generate the realted PolicyChain KUBE-NWPLCY-xxx for the NetworkPolicy associated with the Pod on the current Node.

## Additional context
To express it better, let me give an example. If the current cluster has NetworkPolicyA and NetworkPolicyB, NodeA and NodeB. NodeA has the Pod selected by PolicyA.podSelector, but NodeB does not. At this time, there is no need to generate KUBE-NWPLCY-PolicyA for PolicyA on NodeB.

**Comment by aauren** [comment]
Hey @woooniuzhang thanks for the message. In the future though, could you please fill out the entire issue ticket template? It helps us get a better understanding of the issue and the context of the issue, and reduces the back and forth.

On the surface, I can see what you're thinking here. Unfortunately, making a change like this would break ingress flows in kube-router clusters. By default, kube-router is able to attract traffic from external sources to any node in the cluster, and this is the only point at which the L3 / L4 information represents the actual sender in order to make Network Policy decisions. Because after this, the traffic will either be encapsulated, or it will be NAT'd and this information will be lost. One the next hop, when the traffic gets sent to a node where the pod workload is located, the L3 / L4 source information will be that of the node that proxied the traffic, not the original sender.

As such, every node needs the full network policy so that policy decisions based upon sources not in the cluster can be made.

Out of curiosity though, and to help us track this stuff better over time, can you let us know:
* The size of your cluster? How many nodes do you have and how many pods do you have running in the cluster on average:
* How many pods have NetworkPolicies attached to them?
* How are you quantifying performance? Are the performance problems you're seeing in the control path (setting up the rules) or in the data path (the actual evaluation of the rules)?
* How much performance loss are you seeing because of network policy?
* What is the performance baseline that you are trying to achieve?
* Are you able to subdivide your clusters more? Or are you forced to run with large clusters? If you need to have this as a large cluster, why?

**Comment by woooniuzhang** [comment]
So happly to get your timely reply 😄

- We are doing a survey on the application of NetworkPolicy (v1.3.2) in our production k8s cluster. The cluster has about 400 nodes, each with about 40 pods. We selected 3 of the nodes for stress testing (testing framework as below). The 3 nodes are NodeA, NodeB, and NodeC.  NodeB and NodeC have NetworkPolicy-Pod enabled, but NodeA has not. The we applied 1400 Ingress Type NetworkPolicies (policy.podSelector=Pod3) with Pod3 on NodeC, and each NetworkPolicy contains 20 Rules.

<img width="936" alt="截屏2024-10-13 下午1 36 36" src="https://github.com/user-attachments/assets/7f1741dd-e9d8-4963-82be-65a0be6ff280">


- Then we used the apache ab tool to stress the performance of three calling paths: NodePort (red), ClusterIP (yellow), and PodIP (blue). The results showed that the performance of NodePort path was not significantly different from 0 NetworkPolicies, while the performance of ClusterIP and PodIP path with 1400 NetworkPolicies decreased by about 40% compared with 0 NetworkPolicies (11000QPS->7000QPS)

- We found that 1400 NetworkPolicies generated about 58,000 IPtabels Rules on NodeB.  And we tried to remove the  CustomChains KUBE-ROUTER-INPUT/KUBE-ROUTER-FORWARD/KUBE-ROUTER-OUTPUT on NodeB from the INPUT/FORWARD/OUTPUT chains respectively, but the ClusterIP/PodIP Calling Path performance did not improve. Then we try to flush all the rules in KUBE-NEWPLY-XXX Chains on NodeB, and found that the performance was restored after clearing.

- We believe that in this case, the 58000+ Iptables Rules on NodeB is not effective, so we raised the above question 🤔

**Comment by aauren** [comment]
Hmm unfortunately, I'm not sure that there is a whole lot that can be done here other than sharding the Kubernetes cluster / controlling how many network policies get created. When I asked my question I was mostly hoping that the performance that you experienced was in the control path, because there are probably tweaks that could be made there.

However, the data path is not really something that kube-router has control over. It is ultimately limited by the performance of the netfilter components of the Linux kernel. I don't think that they really envisioned so many iptables rules would be all that common.

I think you had a good thought originally by asking if we could only add rules for the workloads on the pod, however, as I pointed out in my original comment, this would fundamentally break the way that kube-router works for forwarding traffic.

I've thought about a few different ways that kube-router might be able to mitigate this and all of them seem outside the bounds of the project:

* We could have a concept of "ingress nodes" where these ones attract all of the traffic from external workloads and only these ones would carry all rules. The rest of the nodes in the cluster, "non-ingress nodes", would only carry iptables policies that applied to their workloads. However, this would not work for the NodePort use-case without breaking Kubernetes compatibility. The "non-ingress nodes" would have a faster data path, which would fix some use-cases. However, the "ingress nodes" would still have the same data path slowdown that you've found. Additionally, this would add a lot of logic and overhead to kube-router and would introduce a non-standard bespoke workflow to the project, something that we've been trying recently to reduce.
* We could add a concept of service sharding to those ingress nodes. Something like "node group a" would take 1/3 of the service ingress endpoints, "node group b" would take a different 1/3 of service ingress endpoints, etc. But this would add even more complexity to the project in a way that isn't really sustainable.

Ultimately, I couldn't really come up with any good balance towards a solution for your use case. It left me with a couple of thoughts:

* I'm not sure if any other project can handle this better. Have you tried your experiment with some of the enterprise leaders in the CNI space like Calico / Cilium and found that they are able to handle this significantly better than kube-router?
  * Both of the projects that I mentioned use eBPF, so they may have better performance characteristics, but also this is a lot of rules and at some point they are going to have to be processed in the data path, so I'm not sure if they would do better or not
  * In the [ITNEXT benchmarks](https://itnext.io/benchmark-results-of-kubernetes-network-plugins-cni-over-40gbit-s-network-2024-156f085a5e4e), kube-router did good comparatively to both Calico / Cilium, but they obviously did not test at the same scale that you're testing at
* kube-router attempts to be a good CNI for all workloads, but we primarily have been specializing in small to mid size cluster deployments. We are embedded in k3s / k0s because we have minimal overhead for what we do. Its possible, that you may have found the scaling limit for kube-router
* I have been keeping a watch on [Facebook's bpfilter project](https://github.com/facebook/bpfilter) which attempts to implement a feature compatible interface for iptables in eBPF. Its still in the process of maturing and is missing many features, but at some point this might be a relief valve for data path performance issues with iptables.

I don't think that the project has a path forward for your use case for now, but I'll leave this issue open for a bit longer to see if you have any thoughts. Perhaps you have some out of the box thinking for how kube-router might minimally mitigate this issue?

**Comment by woooniuzhang** [comment]
OKK，We probably understand what u mean. We will do further research and express our thanks again 🤝 🤝
