### ISSUE TITLE
Panic when kubelet has --hostname-override *not* set to FQDN

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#23]
Here's the log:
```
ubuntu@osh-sh-ci-01:~$ kubectl logs  kube-router-hkf2d -n kube-system
panic: nodes "kubernetes" not found

goroutine 1 [running]:
panic(0x1596120, 0xc42040a450)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cloudnativelabs/kube-router/app/controllers.NewNetworkPolicyController(0xc420315540, 0xc420314960, 0x0, 0x0, 0x0)
	/home/kube/go/src/github.com/cloudnativelabs/kube-router/app/controllers/network_policy_controller.go:785 +0x413
github.com/cloudnativelabs/kube-router/app.(*KubeRouter).Run(0xc4203c1660, 0xc4203c1660, 0x0)
	/home/kube/go/src/github.com/cloudnativelabs/kube-router/app/server.go:120 +0x710
main.main()
	/home/kube/go/src/github.com/cloudnativelabs/kube-router/kube-router.go:37 +0x13c
ubuntu@osh-sh-ci-01:~$ 
```

In this case kubelet's `--hostname-override` is set to the node's IP address.  I believe that kube-router/app/controllers/network_policy_controller.go around [L785](https://github.com/cloudnativelabs/kube-router/blob/master/app/controllers/network_policy_controller.go#L781) will only succeed if `--hostname-override` is omitted, or is set to the real FQDN on the host.  It should probably not assume anything about the node's name, and pull the node name from the API server.  I'll try to find how that's done and submit a PR if time permits.  Thanks!

**Comment by bzub** [comment]
I said it should "pull the node name from the API server" but now I realize that's what you're already doing in the code.  To support any `--hostname-override` setting, for kube-router in a pod it should be as simple as reading the [$NODE_NAME](https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/kube-router-all-service-daemonset-advertise-routes.yaml#L30) variable from the environment.  For non-pod kube-router invocation I'm not sure the best route yet.. I wonder if we can get the real node name from the kubelet daemon?

**Comment by bzub** [comment]
Ok, for kube-router run on the host and not in a pod, we can use the kubelet REST API:

```
core@node2 ~ $ curl -Gs http://localhost:10255/pods/ | grep -o '"nodeName":"[^"]*"' | head -n 1
"nodeName":"node2.zbrbdl"
```

**Comment by murali-reddy** [comment]
Thanks @bzub for opening the bug. I ran into this issue as well. Problem is kubelet takes any value for `--hostname-override` flag. Value given varies from the OS, to cloud environment etc. In KOPS while provisioning cluster on AWS, this flag is set to FQDN obtained from instance meta-data [1]. In bootkube it is set ${COREOS_PRIVATE_IPV4} [2]. So in generlal any value can be passed to kubelet, it will be used while registering node with the API server. There is no way (atleast to my knowledge) for other components to know what has been passed from kubelet.  Today kube-proxy suffers from same problem, so it supports `--hostname-override` as well. If there is mismatch in whats passed to kube-proxy and kubelet that will still be a problem [3].

Unfortunatley i can not see any clean solution. If you find any soltion please raise a PR or let know i am happy to fix. Thanks!!

[1]https://github.com/kubernetes/kops/blob/master/pkg/model/components/kubelet.go#L151
[2]https://github.com/kubernetes-incubator/bootkube/blob/master/hack/quickstart/kubelet.master#L24
[3]https://github.com/kubernetes/kops/issues/2584

**Comment by murali-reddy** [comment]
@bzub i missed your earlier comment. reading from $NODE_NAME  env variable should work when launched as daemon set. I will test it out on different enviroments will push the change later in the day that fixes atleast for the case of running as daemonset.

**Comment by alexandrem** [comment]
It also fails during setup if node hostname does not resolve.

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x1644ee0, 0xc4200180a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cloudnativelabs/kube-router/utils.GetFqdn(0xc420269ac0, 0x11)
	/home/kube/go/src/github.com/cloudnativelabs/kube-router/utils/fqdn.go:14 +0x141
github.com/cloudnativelabs/kube-router/app/controllers.NewNetworkRoutingController(0xc420190fa0, 0xc4201903c0, 0x0, 0x0, 0x0)
	/home/kube/go/src/github.com/cloudnativelabs/kube-router/app/controllers/network_routes_controller.go:365 +0x134
github.com/cloudnativelabs/kube-router/app.(*KubeRouter).Run(0xc42038f590, 0xc42038f590, 0x0)
	/home/kube/go/src/github.com/cloudnativelabs/kube-router/app/server.go:130 +0x5b7
main.main()
	/home/kube/go/src/github.com/cloudnativelabs/kube-router/kube-router.go:37 +0x13c
```

This problem occurs in our OpenStack cloud where we have nova network making dummy hostnames for the cloud VMs. They don't resolve at all.

Is the purpose of this code is to figure out the public interface IP to bind the service? Because it seems to bind on all interfaces right now.

As a workaround I have to add dummy entry in /etc/hosts for its own IP=>hostname for every VM that runs the kube-router.

**Comment by murali-reddy** [comment]
@bzub thanks for suggestion of using NODE_NAME env, that actually fixed the issued. I would have loved to wait for your PR, but I just had to tidy up the logic spill over multiple places, and put it in a single utility function. So i went ahead made [change](https://github.com/cloudnativelabs/kube-router/commit/d4f32978fbbac6dc2e4cd369d460af0d122b7031) sorry about that. I will keep the bug open to address the concern by @alexandrem, also we still need a way when kube-router is run as agent.

**Comment by murali-reddy** [comment]
@alexandrem the stack trace you printed basically gets FQDN of the node. Since GO standard lib does not have away to get FQDN, i just made up some. Actually this logic need to go away. As @bzub pointed, we will need to get name through which kubelet registers node to the API server. Once we a good way to get this information this information will change.

BTW i just pushed a fix, in case if you are running kube-router as daemonset, this fix will address the problem you have seen.

**Comment by murali-reddy** [comment]
@bzub not sure how want to fix this. I can think of two options.

- just support running kube-router as daemon set. don't see enough reason why we need to run as a system agent, more so when other than kubelet all kubernetes componets and addons are moving to self-hosted model.

- IMO running kube-router as agent, and kubelet is run with --hostname-override option is a corner case, for which i dont want to take dependency of kubelet to infer node name. I would rather explicitly take `--hostname-override` as argument for kube-router

I would prefer option 1. let me know you think otherwise.

**Comment by bzub** [comment]
I was thinking kube-router could take a `--hostname-override` argument like the other k8s master components do, and the user can fix the corner case that the nodeName isn't automatically determined.

**Comment by bzub** [comment]
Yes depending on the kubelet API is bound to break eventually. I agree it's not worth using.

**Comment by murali-reddy** [comment]
thanks @bzub i have added the '--hostname-override' option
