### ISSUE TITLE
Support log level output in configuration

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#240]
We try to make use of basic log levels in kube-router (INFO, WARN, ERROR), however there is no way to filter out purely informational logs, for example. Users should be able to start kube-router with a verbosity or log level setting.

There are even more sophisticated ways to implemenet this too, such as logging to different streams. Suggestions are welcome on the most practical approach.

**Comment by roffe** [comment]
Since we are using [glog](https://godoc.org/github.com/golang/glog) package i suggest we start using it's levels and agree on a common level system to be used when doing code

different -v= levels:
- 0 default, print info messages such as "started sync loop for services"
- 1 additional info, such as printing each service it's syncinc in the sync service loop e.g "syncing service XYZ"
- 2 detailed info, print out things as protocol, adresses etc in more detail. 
- 3 debug print things such as every event processed with as much details as possible.

the code to use the different levels is realy neat and easy to incorporate in existing code.

**Comment by roffe** [comment]
With #294 I changed log level on a lot of the kube-router output so by default it won't be that talky.

It will obey --v or -v flag to produce more verbose output

Imho we can close this issue now
