### ISSUE TITLE
Submit PR to add kube-router to Creating a Custom Cluster From Scratch doc

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#247]
https://kubernetes.io/docs/getting-started-guides/scratch/#network

**Comment by aauren** [comment]
The documentation landscape for kubernetes has changed a lot since this ticket was created and what's there now is a shell of what it used to be and doesn't include a network section at all anymore.

While adding documentation like this would still be good for evangelizing the project, I think most of this has been pushed into the projects themselves now for which we already have documentation. If someone finds another good spot where this can be added feel free to re-open with a link.
