### ISSUE TITLE
Node podCIDR should be EOL'ed 

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#250]
[Node podCIDR should be EOL'ed ](https://github.com/kubernetes/kubernetes/issues/57130)

This is not good for Kube-Router. Part of simplicty of kube-router comes from fact kube-control manager does subnet allocation for the nodes.

Watch out this issue to see how things will evolve.

**Comment by aauren** [comment]
I'm going to close this as stale. While podCIDR may be EOL'd upstream hasn't done any work to make this happen, probably because too many things rely on it. podCIDR is a core part of kube-router, and it would take a significant re-write of kube-router to divorce ourselves from it.

If we get close to taking on that level of work, we can always re-open this issue or open a new one when we're ready for that step. In the meantime, I don't think that having this in the backlog adds much.
