### ISSUE TITLE
Example manifests should ship with Prometheus annotations

### ISSUE THREAD

**Issue by jpds** [cloudnativelabs/kube-router#308]
The example manifests in `daemonset/` should ship with Prometheus metrics enabled out of the box.

**Comment by roffe** [comment]
Hi @jpds and thanks for the feedback!

As of 0.1.0-rc2 metrics has to be explicitly enabled by the user. 

Since the user has to choose the port for metrics I see no reason adding the annotations as the user would have to change them according to what metric port they choose.

Please follow the instructions [here](https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/metrics.md) on how to enable metrics and add the annotations for automatic scraping

Have a nice day!

**Comment by roffe** [comment]
To elaborate: 

Metrics is not enabled by default as most users is gonna run kube-router as a daemonset with host networking meaning the default metrics port *might* collide with existing applications port usage. Therefore it's better not to make assumptions and let the operator configure this according to their own desires.
