### ISSUE TITLE
nodeport did not open a port on host

### ISSUE THREAD

**Issue by zhaofengcumt** [cloudnativelabs/kube-router#357]
when create a service with a nodeport type,the port did not up
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: k8s-webapp-demo
  name: k8s-webapp-demo
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8088
    nodePort: 8099

[root@k8s home]# netstat -anp|grep 8099
[root@k8s home]#

**Comment by murali-reddy** [comment]
@zhaofengcumt this is expected behaviour. Linux LVS/IPVS acts more like router/forwarder or what is called as LVS director. There is no active listener.

Snip from http://www.austintek.com/LVS/LVS-HOWTO/HOWTO/LVS-HOWTO.what_is_an_LVS.html

`
The director is basically a router, with routing tables set up for the LVS function. These tables allow the director to forward packets to realservers for services that are being LVS'ed. If http (port 80) is a service that is being LVS'ed then the director will forward those packets. The director does not have a socket listener on VIP:80 (i.e. netstat won't see a listener).
`
