### ISSUE TITLE
Explore using IPVS direct routing mode

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#40]
Issue opened to track DR mode feature.

Initial research to put in this issue:
- [x] DR mode benefits over NAT mode
- [x] Challenges DR mode raises in different kubernetes environments

**Comment by murali-reddy** [comment]
This is most efficient mode to use, but unfortunately there are constraints due to which its very non-trivial to achieve.

Please see http://www.linuxvirtualserver.org/VS-DRouting.html
https://www.centos.org/docs/5/html/Virtual_Server_Administration/s2-lvs-directrouting-VSA.html
http://www.austintek.com/LVS/LVS-HOWTO/HOWTO/LVS-HOWTO.arp_problem.html

We need L2 adjacency between the IPVS/LVS director and real server. In the context of kubernetes it means each node need to have L2 adjacency to pods running on same or different nodes. As i understand we need to do some trickery (not sure even its possible).

Please use ipvsadm to try the scenario to see even its possible. I could not figure a way.

Also please see https://www.youtube.com/watch?v=KJ-A8LYriGI&t=204s, though it seems more like for north-south traffic.

Current container orchestration platforms (Docker swarm, Meso Minuteman) that uses IPVS does not support DR mode either. Please see if there are any efforts in those project to get DR mode.

**Comment by bzub** [comment]
Adding a WIP design done by @Thoro

[masquerading with asymetric routing](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Masq-Async-Routing.xml#R7Zxbc5s4FMc%2FjR%2BXQTcMj7m03Z3p7mQmndnmKSODbLPBiAElcfrpV4CwQSIJsYGQxp1pC0dCgH76Hx1d8AxdbLbfUpqs%2F%2BYBi2bQDrYzdDmD0LOJ%2FDc3PJUGAp3SsErDoDSBveE6%2FMWU0VbW%2BzBgWSOj4DwSYdI0%2BjyOmS8aNpqm%2FLGZbcmj5l0TumKG4dqnkWn9NwzEWlmBbe8T%2FmThaq1u7RKVsKD%2B3Srl97G63wyiZfGnTN7QqiyVP1vTgD%2FWTOjLDF2knIvyaLO9YFFetVW1ldd9fSZ199wpi0WXC7AC9UCje%2FXuWerP0Jm0AZdY0HYtgJAlC3YiWeL5IpVHq%2FwoyESZDwJoAddybWvHLxNPVVUKts1zr8UmkgYgD1OWhb%2Fooshgy%2FOEh7EogJHzGbmUFnoveFY2ivwCGoWrWB5HbJkX9cBSEUpWZ8oseCKtWUL9MF79yE8u%2F8DSsgyj6IJHPC0eBAWUuUs%2FzylSfsdqKY7vssVSppi1pyo0vyXb1kyqNr8xvmEifZJZVCqqWoJq%2BdjB5fljox2VtnWtCSFlo6rprnZF7%2FHJA0WwnaZr1D4LZLtWpzwVa77iMY2%2B7K3nsgUmeWoUxnc5nLztskChqVFj21D8rB3f5Fksos6uWBrKx2WpulBWYPr0s35Sy5%2Bf6hf8x4R4Uo4gxy9N%2B%2Bf9zguq4CVEGb9PffXWULkMmq5YVb2lKa%2BPFzGmLKIifGj6gWOYQENgBqQKwWa7yr2p5YeZzy1JQlZPpv5vwghott5B0tq5jRzXm7e1c%2BWJqpTKs8Gapr7TBYuupPhEyHNtLbgQfPOs6Cpl%2BpJG8Yw9KAjM3YaCADYVVGWpC4ig42F5IwhoL5qbWsrzAtpr5qaeNqiAkCkg%2FF4CQicBvU1A2Gl2QQCj0QSED4WVPYbCX7PMeuRpEUElt6XpE3HDTccHsW2GDjZoAddD6DAfxfN5ddc31eiBmM4PvpfzM8Pzjnry%2BSYp3N8tjYPbRNZXsmYpjTIroknZhj%2BJrIDuDU1VeS3xuNMDPUBGjyfsSUoKVIP4KQQU1cOcIorOg1q7qSHkeaNFFABNUENaTG557jgyahnYvp%2BMTiPbIwNz5LnjyWicAO8YGYFxNOSYGqqa8juIyOk%2FwEv8zyspUq08vCKpeQ9DJuC%2Bzo7FwVm%2BHpG%2FdkSzLNTYaDiWrs%2F81jnqhUswsV%2BqtFcbb61KSEvAW9k6t3F1h6t8%2Br4ebmvxtj6xXYpRXQVrSxNaQUbgrhdUKtgoqMC2e%2B1uJL3eSTIQENYqLM%2BZI%2Bp8AJLQI00AGB1GEtuvFNQfyWpdrU9NLpnTrslg7i3sj6BJos8IOt5hJPWCdlNUA5DsEF7WSMY8Zk2MmXwWYYIuzF%2FDaBe7xIE6a%2BkepYbdALexd%2BECOR9BxRhryPTZwq7s9ZVNo6Ae2XeY8z%2Bxf509ghoy51D2WkHIHY59hyWEV9g%2F56b7aBW73mDy7PXBpo6sc%2B%2BtO5CO7GVF06daNrXNo%2FMDV%2FfZN6WyxIMbVoe59DeGBr%2BBiyC6ssGBzcQoyBvORXQYNJ9IYgL7IYk9OBjJef8kj9jmNRGSeK4DONR16wXp%2FX%2BPJPufDPkdSLp9dcJ6QfZwJPufDPkdSKImAHCoJpE%2BrTVcP1k98onkS1Iydt4eqkk4nCYR7J3kcrmEz0xrOQuHfISIB8x70iQYUZPm1MblP2c%2FDJqT2TZ%2FzPRn93UcoqNE5p7FtpYE7ecbTecNpuZwYv8NhAct4LiWbcEXvoDQvpSYLMojVpfest%2BqibLykmN8AIHM8cT1pNV1zDJRdyQy6GiqyzaZDKYuc2CwU5f25dBH19dIMF3cgOmNqS9zbPB2mDIDQcXfKX8u9k79HjH3LwxGE5vjgxPNPj%2F%2BG1Wb2NzWOu3I8pg51ze4S%2BI0mKC5ueluqL4Pm8O2QwU2t8wR3ycjCTyNJDZJDqcuc1ly2pHlOJ87Y23kjD2z%2FxpMXea4LUweMhpsTDmZloylD2G%2BKbSlF2vLy9KsyKunTVKffajNbaoNE2CqDbeg7WNrJTbHcX9dTdgf9hEJYq9R3wSZSmr7TqkXJZljtGmHDsdMXr4hdLCbSHab6Mdwbi%2BMtLr%2BMEdj8upzo9Sc2W7H%2FxihAzGHWdeq85E3o3EQyQqSh2LNitf071i5T2YiwHoJE5pzFsQzlbSbzT9SSvJ0%2F%2Fs55Qz9%2FjeK0Jf%2FAQ%3D%3D)

**Comment by murali-reddy** [comment]
Elegent solution for DSR(Direct Server Return) in [Microsoft Ananta](http://conferences.sigcomm.org/sigcomm/2013/papers/sigcomm/p207.pdf)

Take a look at Fig 7. It can be applied to kube-router as below.

Packet flow for the first packet

step1: client->service vip
step2: Node select an endpoint performs IP-IP encap with same source, and destination as pod IP
step3: Destination node intercept perform decapsulation send packet to pod
step4: pod gets the packet, respond directly to the client IP.

Each node to need to be aware of the flows and need to be consistent hashing for subsequent packets as detailed in the paper.

**Comment by murali-reddy** [comment]
Figure 2 of [google's maglev](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44824.pdf) they use GRE for DSR

**Comment by murali-reddy** [comment]
How Facebook does DSR with IP-IP 11.00 to 16.00 https://www.usenix.org/conference/srecon15europe/program/presentation/shuff

**Comment by murali-reddy** [comment]
https://www.slideshare.net/jschauma/l3dsr-overcoming-layer-2-limitations-of-direct-server-return-load-balancing

Use of DSCP to achive DSR.

**Comment by andrenth** [comment]
This post also describes Facebook's solution: https://www.facebook.com/notes/facebook-engineering/under-the-hood-network-implementation-for-world-ipv6-launch/10150873176303920/

**Comment by Thoro** [comment]
IPVS Configuration for FWMARK service with DSR

iptables:

```
iptables -t mangle -A PREROUTING -d 185.208.132.3 -m tcp -p tcp --dport 333 -j MARK 5
iptables -t mangle -A OUTPUT -m mark --mark 5 -d 10.253.10.12 -j DSCP --set-dscp 3

ip rule add iif eth0 fwmark 0x5 lookup 100
ip route add local default dev lo table 100
```
<-- here it's necessary to put the ingress interface, or the fwmark is deleted on output, otherwise the packet is routed again to lo, and be careful with the route, to really add it to the table, otherwise you kill the IP connectivity ;)

ipvsadm:

```
ipvsadm -A --fwmark-service 5
ipvsadm -a --fwmark-service 5 -r 10.253.10.12:333 --masquerading
```
<-- here it's important that a port is defined, otherwise 0 is used and the packet is dropped

pod iptables:

```
iptables -A INPUT -m dscp --dscp 3 -j DSTWRITE --to-destination 185.208.132.3
```
