### ISSUE TITLE
push docker images for other architectures with github release

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#503]
We can build kube-router docker images for other architectures manually. So push the docker images other architectures as well with github release.

**Comment by runningman84** [comment]
I have spent some time creating a multi stage docker build for kube-router with multi arch support:
https://hub.docker.com/r/runningman84/kube-router
https://github.com/runningman84/docker-kube-router
I have tested these images in a mixed arm64/amd64 env...

**Comment by bzub** [comment]
Oh I see you did the manifest work already (https://github.com/runningman84/docker-kube-router/blob/master/manifest.yaml). Awesome!

**Comment by runningman84** [comment]
I am looking forward for the official multi arch image! If you have any questions regarding my build feel free to ask...

**Comment by runningman84** [comment]
@bzub any news regarding the multi-arch release?

**Comment by wilmardo** [comment]
@murali-reddy @bzub What is holding this back? There is #336 and #445 so to me it seems that all the prerequisite are there.
I looked if I could take a stab at fixing this myself but there doens't seem a CI for releasing the images? If someone could point me in the right direction I am game :)

Would be really nice since kube-router seems the way to go for low power clusters (not that much overhead).

**Comment by mrueg** [comment]
Linking this one here as well: https://github.com/cloudnativelabs/kube-router/pull/885

**Comment by aauren** [comment]
This is resolved via #885, #735, #847 & #839
