### ISSUE TITLE
kube-router vs kubernetes 1.11 ipvs

### ISSUE THREAD

**Issue by runningman84** [cloudnativelabs/kube-router#510]
I am wondering what is the difference between kube-router and the new native ipvs proxy support in 1.11?

https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/

**Comment by thardie** [comment]
For a start, doesn't look like native supports BGP...

**Comment by roffe** [comment]
Also kube-router replaces kube-proxy so instead of having kube-proxy + overlay networking you just have kube-router running

**Comment by asteven** [comment]
I still think this is a valid question.

May I re-ask the OPs question as:
What is the difference between kube-router's service proxy and the new native ipvs proxy support in kube-proxy >= 1.11?

It was mentioned that kube-router supports DSR.
Are there other differences?

If kube-proxy in ipvs mode does >95% the same as kube-router then IMHO it's hard to justify maintaining the redundant code.

**Comment by murali-reddy** [comment]
> If kube-proxy in ipvs mode does >95% the same as kube-router then IMHO it's hard to justify maintaining the redundant code.

It depends on the perspective you look at it. Many users of kube-router like the fact that its one simple cohesive solution that would other wise mean installing two or three solutions running as pods.

Having said that if some one wants to use kube-proxy they can always use kube-proxy along with kube-router.

Other than DSR kube-router also expose different IPVS lb methods to be applied to services. But to be honest from service proxy perspective neither kub-proxy or kube-router is doing any thing substantial they are just automating configuring IPVS services and objects

**Comment by runningman84** [comment]
From my experience kube-router preserves the client ip address and kube-proxy masks it by NAT.

**Comment by asteven** [comment]
@murali-reddy Thanks for sharing your thoughts.

Don't get me wrong. I love the simplicity of kube-router. I'm planning on going in production with it. It's the perfect fit for on prem bare metal clusters. Especially if you have a datacenter full of vms and servers to integrate with.

But I am a bit concerned that it does not have _that_ many users/developers/maintainers. ~130 open issues going back to mid 2017 does raise some questions. I am not complaining, this is open source. I'm perfectly ok with scratching my own itches. Which is also why I decided to start digging into the code btw.

The best code is the code you don't have to write. The second best code is the code you can remove and no longer have to maintain. That's why I wanted to have a better understanding of what the differences between kube-proxy and kube-router's service proxy are if any.

Thanks also to @runningman84 for your input. That's an important point.

**Comment by thardie** [comment]
For us, the most important feature is BGP. The fact that we can have our clusters advertise external IPs to our routers and attract traffic and have our routers to ECMP is the main reason we chose kube-router.

DSR is a nice to have, but not top priority.

**Comment by mcarbonneaux** [comment]
DSR + BGP make possible to implement multilevel load balancer with kubernetes without external load balancer...
DSR avoid the reroute the traffic to the node who receive the traffic...
and coupled with bgp any node that act as LB DSR can receive the traffic...
and coupled with maglev... and ingress controler ...

like : https://vincent.bernat.ch/en/blog/2018-multi-tier-loadbalancer

with kube-router you can do that... not with k8s kube-proxy...
