### ISSUE TITLE
k8s is runing on openstack  virtual machine 

### ISSUE THREAD

**Issue by Blue-Skies-firststar** [cloudnativelabs/kube-router#515]
when  k8s is runing on openstack  virtual machine  but pod network is not work 
who can help me?

**Comment by roffe** [comment]
Hi @Blue-Skies-firststar 

There is a Kubernetes slack channel where people come together to discuss problems and solutions
https://kubernetes.slack.com/messages/C09NXKJKA

Kube-router also has one
https://kubernetes.slack.com/messages/C8DCQGTSB

And the Special Interest Group for Openstack
https://kubernetes.slack.com/messages/C0LSA3T7C

**Comment by murali-reddy** [comment]
@Blue-Skies-firststar There are anti-spoofing checks that need to be disabled.  Otherwise there is nothing that is specific to OpenStack that interferes with Kube-router. Please first ensure this pre-requisite and see if this helps.

https://github.com/kubernetes-incubator/kubespray/blob/master/docs/openstack.md

**Comment by Blue-Skies-firststar** [comment]
Thank you. The network  is available
