### ISSUE TITLE
Annotation to support changing IPVS timeout per service

### ISSUE THREAD

**Issue by roffe** [cloudnativelabs/kube-router#598]
As discusse in https://github.com/cloudnativelabs/kube-router/issues/521 

A per service annotation that lets one controll the IPVS timeout

Default IPVS timeout value:

ipvsadm -l --timeout
Timeout (tcp tcpfin udp): **900** 120 300

TCP in the kernel has:

Default TCP timeout value:

tcp_keepalive_time = **7200** (seconds)
tcp_keepalive_intvl = 75 (seconds)
tcp_keepalive_probes = 9 (number of probes)

Other related things around:
https://github.com/cloudnativelabs/kube-router/pull/583
https://success.docker.com/article/ipvs-connection-timeout-issue

**Comment by znoodl** [comment]
https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/

The similar function is `Session Affinity` and has been supported in kube-router.

**Comment by Simon-Li** [comment]
I'm interesting to look into it.

**Comment by dannyk81** [comment]
Just wanted to add my 2 cents as I was investigating a similar issue recently.

Since Kernel 4.13 all the `tcp_keepalive_*` sysctls are namespaced so a container launched will not inherit their value from the host node.

These sysctls must be tuned on the container namespace, in K8s it is done via `securityContext` spec attribute (though other methods are possible). 


As for IPVS tcp timeout, AFAIK it is a global timer and I don't see a way to tune it per service, additionally increasing this timeouts will also increase significantly the recovery of a node failure, as traffic will get blackholed. 

In a separate discussion it was mentioned that default timeout might in fact be lowered even more. 

https://github.com/kubernetes/kubernetes/issues/71358#issuecomment-503234702

**Comment by sanjmonkey** [comment]
Adding my own $0.02, I would love to have the option to adjust this in IPVS, per-service, if at all possible.  

Obvious use case; long-lived TCP sessions which aren't very chatty.  I fell across this recently when putting in some RPKI-RTR boxes, who's suggested default refresh_timers of 3600s and often get cut off by IPVS in the middle as the application is often silent for > 900s.

**Comment by bhcleek** [comment]
Does https://github.com/cloudnativelabs/kube-router/pull/882 provide a path forward for users such that this issue should be closed?

**Comment by aauren** [comment]
Yes, I believe that it does, thanks for pointing it out and helping us groom issues @bhcleek!

While there is other discussion on here about changing tcp timeouts, I think that this is a more complex issue and if people are still interested in that they're welcome to raise another issue to talk more about it.

However, #882 does makes kube-router now take into consideration sessionAffinity timeouts for IPVS in a way that is now compliant with: https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-ipvs and as such I'm closing this.
