### ISSUE TITLE
Removing ExternalIP Fails to Withdraw Route

### ISSUE THREAD

**Issue by magikman** [cloudnativelabs/kube-router#639]
I am using externalIPs to advertise out anycast BGP routes from kube-router. Advertising works as you'd expect: I add an externalIP and it is advertised. Unfortunately when removing the externalIP, the route is never withdrawn from my peers. 

Running kube-router version v0.2.0-beta.7, built on 2018-06-08T09:34:34+0000, go1.8.7

**Comment by magikman** [comment]
@murali-reddy If you can provide a bit of insight into which package this bug likely exists in, I will start hunting for it.

**Comment by murali-reddy** [comment]
@magikman please see

https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/ecmp_vip.go

this is where all service VIP's  that are to be advertised and withdrawn are identified

**Comment by mk01** [comment]
@magikman @murali-reddy 

it is because the on update() methods are not considering previous state.
in this PR https://github.com/cloudnativelabs/kube-router/pull/669 is implemented one way to fix (by remembering currently advertised list of ext ip)

another way would be to pass oldObj on update too and take the previous list from there. perhaps it would be even better.

mk
