### ISSUE TITLE
metrics: Add port configuration and Service definition

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#67]
For #66 - Phase 1

- Add a `--metrics-port` option to change the port.
   - `--metrics-port=0` means disabled. Default port should be uncommon.
- Provide a k8s Service definition for kube-router metrics port to our example manifests

**Comment by roffe** [comment]
bzub I added the first part via #288, however there is no logic to disable metrics by setting the port to 0. Will see if i can compose a PR to fix that as well

**Comment by roffe** [comment]
@bzub i think a service definition is not going to work for the metrics since every node is going to have it's own set of metrics and if prometheus scrapes that endpoint every 15 sec the results is going to vary depending on which node it gets metrics from.

I have provided examples on how to setup annotations for prometheus to scrape each node individually [here](https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/metrics.md)

--metrics-port is implemented and setting it to 0 will disable metrics in whole

**Comment by roffe** [comment]
Imho we have covered this with examples and documentation now, closing. feel free to re-open if stil needed
