### ISSUE TITLE
Drop packets in INVALID state

### ISSUE THREAD

**Issue by roffe** [cloudnativelabs/kube-router#709]
Should we implement?

https://github.com/anfernee/kubernetes/commit/a07169bcadf3c35ff456c17bed970ccbca0963cb

https://github.com/kubernetes/kubernetes/issues/74839

@murali-reddy

**Comment by roffe** [comment]
https://github.com/kubernetes/kubernetes/pull/74840#issuecomment-483154420

**Comment by NaPs** [comment]
Hi, this issue is actually a real problem due to this "bug": https://bugzilla.netfilter.org/show_bug.cgi?id=693.

TLDR; Sometimes, netfilter fails to masquerade some packets and according to a netfilter developer, this is perfectly normal. The recommended solution is to drop packets marked INVALID by the conntrack:

> I close the bug as invalid, because this is the way how the sytem works: in a natted environment INVALID packets must be dropped.

In practice, I can observe packets with source address in PodCIDR outside my clusters.

As it is difficult to add iptables rules since kube-proxy/docker/kube-router are already doing their stuff here, I think it would be convenient to add an option to create this rule in Kube-Router (such as Calico's DisableConntrackInvalidCheck option).
