### ISSUE TITLE
kube-bridge interface disappears after Master node reboot

### ISSUE THREAD

**Issue by sbrohi-att** [cloudnativelabs/kube-router#743]
**Kubernetes Version: v1.11.9**
**Kube-router version: v0.2.0**
**Docker Version v1.13.1-74**

I have noticed that when the master node is rebooted, the **kube-bridge** interface disappears. I noticed this after examining the route table post-reboot and noticing that this interface was gone, which led to a disruption of my application services. 

A few questions: 

1. What causes this to occur? 
2. How can we persist the kube-bridge interface between master reboots? 

This is the interface that was here before the reboot:
`10.0.0.0        0.0.0.0         255.255.255.0   U     0      0        0 kube-bridge`

**Comment by andrewsykim** [comment]
This is intentional, kube-bridge is created by kube-router but it will not persist reboots unless you add it to `/etc/network/interfaces`. 

The rational is that you lose your containers on a reboot so no reason to keep the bridge interface as well. In most cases kube-router should start back up and re-create the bridge interface. 

Please reopen if that doesn't answer your question :)
