### ISSUE TITLE
restrict advertising all cluster IP's

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#75]
Even though advertising cluster IP's is optional (with --advertise-cluster-ip). Once flag is enabled all the cluster IP's are advertised which is not desirable. For e.g Db. so use an annotation to selectivley advertise the service which user request to.

**Comment by asteven** [comment]
I'm thinking of taking a shot at this.

What do you think about the following proposal?

Obviously use the existing cli flags to set the default behavior cluster wide:

```
--advertise-cluster-ip true|false
--advertise-external-ip true|false
--advertise-loadbalancer-ip true|false
```

Then use the following annotations per service to override the defaults:

```
kube-router.io/service.advertise.cluster true|false
kube-router.io/service.advertise.external true|false
kube-router.io/service.advertise.loadbalancer true|false
```
Personally I would deprecate kube-router.io/service.skiplbips in favor of kube-router.io/service.advertise.loadbalancer because it's more explicit and would be consistent with the others.

**Comment by murali-reddy** [comment]
Sounds good to me. Make sense to normalise the naming convention to `kube-router.io/service.advertise.*`
