### ISSUE TITLE
Kubelet flag --allow-privileged is removed in 1.15

### ISSUE THREAD

**Issue by wilmardo** [cloudnativelabs/kube-router#761]
See:
https://github.com/kubernetes/kubernetes/pull/77820 < PR
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#node < Changelog

They have been deprecated since 1.12 or earlier. So the [requirements ](https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#requirements)aren't valid anymore (couldn't get kube-router to work on 1.15.1 with containerd).

Related: #482

**Comment by murali-reddy** [comment]
@wilmardo Agree on the needed update to the documentation. 

> So the requirements aren't valid anymore (couldn't get kube-router to work on 1.15.1 with containerd)

I am able to use kube-router with 1.15.1. Perhaps this is different  issue? What issue/error are you seeing  when using kube-router with 1.15.1?

**Comment by wilmardo** [comment]
Which requirements are not needed anymore? I could update the docs accordingly.

There were no errors in my deployments (not that I could see), just no network between nodes. I will try to reproduce this on my laptop (the error was on my arm cluster at home).

**Comment by andrewsykim** [comment]
Any updates on this?

**Comment by wilmardo** [comment]
No from my side, I am not using kube-router anymore but I am willing to improve the docs if the information is provided :)

**Comment by edgan** [comment]
I am seeing the same problem. I would love to hear an update before I switch to something else.

**Comment by edgan** [comment]
I have continued to dig, and found even going back to 1.14 in my situation didn't fix it. It ended up, at least with 1.14, being an issue of toleration. I have previous setup kubernetes in AWS, but now I am trying to setup a cluster in Azure. I haven't yet configured the cloud provider. Which created a new toleration that kube-router didn't accept. I used the command below to find the additional toleration.

This problem is one of the things I really dislike about Kubernetes. It doesn't just say "Error: error message". You have to make sure to check everything by dotting every i and crossing every t.

I am going to both try upgrading back to 1.16 that I started with and also configuring the toleration. I am also going to try no additional toleration and a fully configured cloud provider.

### Command
```
kubectl get nodes -o yaml | less
```
### Toleration
```
+      - effect: NoSchedule
+        key: node.cloudprovider.kubernetes.io/uninitialized
+        value: "true"
```

**Comment by edgan** [comment]
It seems to have just been the toleration issue. I was expecting to have to make the change below, but found it both didn't work and wasn't needed. The existing securityContext of privileged: true works for me on 1.16.

Change:
```
         securityContext:
-          privileged: true
+          allowPrivilegeEscalation: true
```

**Comment by murali-reddy** [comment]
@edgan sorry what exactly is the issue you are facing with kube-router. i thought original issue just needed documention update.
