### ISSUE TITLE
Running Kubernetes without service proxy

### ISSUE THREAD

**Issue by salanki** [cloudnativelabs/kube-router#893]
In a full BGP setup, given that `kube-router` announces Cluster IPs via BGP, it should be possible to run Kubernetes completely without a service proxy and rely on the routing infrastructure to route traffic to services as well as load-balance using ECMP.

1) Is this configuration possible?
2) Is anyone doing it?

My reasoning is that kube-router BGP is required to reach Pods, since it adverties the nodes Pod CIDR via BGP  there is a failure situation where kube-router is dead, but service proxies from other nodes still forward traffic to the Pod CIDR on that node that is now unreachable. Assuming that the routing provided ECMP is good enough for load balancing, taking out service proxy complexly would make that failure scenario and make the setup simpler.

**Comment by aauren** [comment]
This is not a configuration that is currently possible with kube-router. In order to maintain compatibility with the Kubernetes service API we have to run lPVS on the nodes, vanilla BGP does not give enough knobs to fulfill all of the various feature flags that are needed to be compliant with the API. Additionally ECMP leaves much to be desired as the only form of load balancing. As such, this means that the Node's IP address (and not the pod's IP address) is always the next hop advertised for any service VIPs whether they be ClusterIPs or ExternalIPs.

Regarding your concern, if kube-router were to die, I think that BGP routes would be just as susceptible, if not more so, to failure as the Linux kernel routing services on the node. kube-router itself is never in the network traffic data path. Instead kube-router configures other Linux services to handle this work for it. Things like iptables, IPVS, local routes, ipset, etc. are all part of the data path. When kube-router dies unexpectedly, all of these definitions stick around regardless of whether kube-router is running or not.

While there are knobs to handle unexpected BGP termination, these all, for better and worse, have timeouts associated with them. So overall, I would expect the Linux kernel routing mechanisms to last longer than BGP in the even that kube-router dies.

Additionally, it is definitely recommended that you implement some sort of process health checking / supervision to kube-router. This happens automatically via k8s concepts if you use the daemonset manifests provided in this project, but if you run it outside of that, this is something that you would have to handle yourself.

All of that being said, as you mentioned, kube-router definitely has the ability to advertise the pod IP address CIDRs via BGP. So if you were to register your pod IP addresses directly in a service discovery mechanism or other load-balancing system, you could effectively do what you're trying to do.

**Comment by salanki** [comment]
A lot of what you are saying makes sense. Right now, services are susceptible to outage if kube-router crashes. The service proxy on the source nodes will send traffic to the Pod IP, that is no longer in the routing table of the network infrastructure, so traffic will be blackholed. Kube-router will be restarted, but it still leaves ~20s where traffic is blackholed.

**Comment by aauren** [comment]
Am I correct in understanding that this happens because the BGP advertisement for the pod CIDR gets withdrawn? If so, have you guys played with the `--bgp-graceful-restart` and `--bgp-graceful-restart-deferral-time` options?

**Comment by murali-reddy** [comment]
Agree with Aaron. If you use BGP graceful restart, data path coninue to work even if kube-router is crashed.

regarding running Kubernetes without service proxy it will break many of kubernetes networking underpinnings. First for the east-west traffic i.e) service-to-service traffic, service discovery and load balancing is provided by service proxy running on the source node where traffic originated from the pod. Using ECMP is 2-level load balancing. Load balancing the traffic to the nodes and subsequently proxy on the node load balancing to the pods. Also service types like `NodePort` would need a proxy on the node.

**Comment by salanki** [comment]
Yes, the idea I had in mind is the 2-level load balancing as you described. Traffic over the network is sent with the ClusterIP as destination, and then load balanced to pods on the receiving node. As I see it, it has the following advantages:

1) Assuming your cluster has a lot of ingress traffic from the outside world, you still need to manage L3 load balancing and failure detection / failover for the external service endpoints, which will be done via BGP / MetalLB in most bare metal deployments.
2) You can then leverage BFD and other fail-fast protocols to quickly detect node failures and remove that node from the traffic path, both for external services and internal cluster services. You now only need to design and worry about one fast-failover mechanism, instead of two; One on the network layer for external traffic, and one inside K8s for service-service traffic.
3) Traffic will automatically be routed to the nearest node that can handle it, instead of getting load balanced over nodes that can be very close or very far away from the current node. [Service Topology](https://kubernetes.io/docs/concepts/services-networking/service-topology/) now solves this.

This is obviously not for every use case, and I appreciate you entertaining my thought experiment here.

**Comment by aauren** [comment]
@salanki Unfortunately, I don't think that Kubernetes or kube-router, at least in their design or intention, are well suited to what you're trying to do. While I think that you could make this work for a limited use-case, it would never be feature compliant with the entire service spec. Additionally, I think that you would ultimately find that it came with a bunch of small networking gotchas that were difficult to troubleshoot, support, and document.

The aim of kube-router is to be as fully compliant with the Kubernetes service spec as possible, as such, this isn't a mode of kube-router that we would be able to support.
