### ISSUE TITLE
clients of UDP applications receive errors when the UDP application is updated

### ISSUE THREAD

**Issue by bhcleek** [cloudnativelabs/kube-router#899]
##### reproduction

1. deploy kube-router with `--ipvs-graceful-termination` set
1. do not set `hostNetwork` in cluster DNS pods
1. scale cluster dns to a single pod to simplify to a base case
1. wait 5 minutes if any cluster dns pods were deleted
1. deploy a client application that makes DNS requests against the cluster's DNS (e.g. https://gist.github.com/bhcleek/cba55971319bf23639ee4f3d1718ae34).
1. start following the client applications logs
1. delete the single cluster dns pod and let it be replaced

##### expected behavior
The DNS client should only see errors for those requests that were routed to DNS before the pod terminated (note this is not about termination state - look for when the pod is actually removed)

##### actual behavior
the DNS client experiences _waves_ of errors for the duration of the IPVS UDP timeout period, 5 minutes by default

##### notes
The reproduction steps use DNS as an example, but any application that uses UDP requests and responses similarly DNS will see this problem.

This seems to be related to the IPVS connection tracking. `ipsvadm --list -u $CLUSTER_DNS:53` can be used to see the realservers backing the cluster DNS service and `ipvsadm --list -c | grep $CLUSTER_DNS:53` can be used to see that IPVS is tracking and using connections for deleted pods even after the pods no longer show up in the realservers backing the cluster dns service.

It's worth noting that with kube-router's `--ipvs-graceful-termination`, the realserver is weighted to 0, but that doesn't really seem to impact the occurence of these errors one way or the other; this problem is fundamental to IPVS' connection tracking.

Similarly, `conntrack -D` that kube-router runs when doing graceful termination of UDP services does not impact IPVS' connection tracking.

##### workarounds
One simple workaround is to set a `preStop` hook in the cluster DNS pods that waits for IPVS UDP timeout period before returning and also set the pods t`erminationGracePeriodSeconds` to at least the IPVS UDP timeout period (I've used IPVS UDP timeout period + 30 seconds to maintain the grace period relative to when the SIGTERM is actually sent in light of the `preStop` hook's delay).

relates to kubernetes/issues#81775

**Comment by andrewsykim** [comment]
This seems like a side effect of using conn_reuse_mode which opts to reuse backends if an existing source address + port exists in the connection tracker.  

We've seen similar occurrences of this in kube-proxy which is why we opted to skip graceful termination for UDP in https://github.com/kubernetes/kubernetes/pull/77802. If you read the full discussion there, it's noted that this doesn't fix the issue entirely, it only alleviates it by reducing the chance of conflicting ports. In addition to skipping UDP for graceful termination, it's noted you can configure the UDP timeout (with `ipvsadm --set`) which should significantly reduce the # of connection entries in IPVS which will also reduce the chance of conflict. Alternatively you can disable `conn_reuse_mode` but that comes with performance tradeoffs.

**Comment by bhcleek** [comment]
Thanks, @andrewsykim. It does seem like avoiding graceful termination for UDP would be worthwhile here.

**Comment by bhcleek** [comment]
I see errors up to the IPVS UDP timeout even after the graceful termination period has elapsed and kube-router has deleted the IPVS real server entry. Doesn't that imply that avoiding graceful termination for UDP would still see the same problem (potentially at the same level as currently experienced)?

**Comment by andrewsykim** [comment]
> I see errors up to the IPVS UDP timeout even after the graceful termination period has elapsed and kube-router has deleted the IPVS real server entry. Doesn't that imply that avoiding graceful termination for UDP would still see the same problem (potentially at the same level as currently experienced)?

Some errors are expected on source port conflict even after a real server is deleted, but enabling `expire_nodest_conn` should reduce the # of errors since IPVS will try to expire the connection on failure (more details in the PR I linked). I don't think the same applies when we just set the weight to 0. This in addition to reducing the UDP timeout helps since the chance of port conflict is significantly less when the UDP "connection" expires quickly.

**Comment by bhcleek** [comment]
I'm seeing a significant a number of errors that come in waves for up to UDP timeout period even after the realserver has been deleted. I'll try running kube-router with `--ipvs-graceful-termination` off to verify in case something about setting the weight to 0 before the real server is deleted causes the connections persist unless you're confident that there should be no difference between the magnitude of errors after a real server that's been weighted to 0 and then deleted vs a real server that is deleted without weighting to 0.

**Comment by andrewsykim** [comment]
> unless you're confident that there should be no difference between the magnitude of errors after a real server that's been weighted to 0 and then deleted vs a real server that is deleted without weighting to 0.

I am actually saying the opposite, the amount of errors should be LESS if you delete the real server right away vs setting the weight to 0 during the pod's termination grace period and then deleting it.

**Comment by bhcleek** [comment]
Disabling `--ipvs-graceful-termination` does impacts neither the magnitude of errors nor the duration during which they occur. Of course, adjusting the udp timeout does.

**Comment by bhcleek** [comment]
Closing this. Changes to the 5.9 kernel resolve this:
* https://github.com/torvalds/linux/commit/35dfb013149f74c2be1ff9c78f14e6a3cd1539d1
* https://github.com/torvalds/linux/commit/f0a5e4d7a594e0fe237d3dfafb069bb82f80f42f
* https://github.com/torvalds/linux/commit/f9200a52eedfe96ae8d9cbf68a363f5409a46117
