### ISSUE TITLE
Conflict with metallb

### ISSUE THREAD

**Issue by zerkms** [cloudnativelabs/kube-router#938]
My apologies about lack of details, but I will put more as long as I find anything.

I have a on-premises kubernetes installation (at the moment runs on 1.17.4) with metallb v0.9.3.

And after upgrading kube-router to 1.0.0-rc5 I lose connectivity with any `LB` services exposed by metallb. At the moment I run 1.0.0-rc4 and experience no problems (but a minior thing I reported a few minutes ago as well: https://github.com/cloudnativelabs/kube-router/issues/937)

It just does not respond to arp requests anymore.

Again, my apologies to the lack of details, this issue is just to raise awareness before I dig deeper.

**Comment by caesarcxiv** [comment]
Same issue here - tracked it down in log

E0618 01:15:50.879457       1 service_endpoints_sync.go:343] Failed to verify and cleanup any mangle table rule to FMWARD the traffic to external IP due to Failed to cleanup iptables command to set up FWMARK due to running [/sbin/iptables -t mangle -C PREROUTING -d 192.168.20.180 -m tcp -p tcp --dport 443 -j MARK --set-mark 2267 <nil> --wait]: exit status 2: iptables v1.8.3 (legacy): MARK: trailing garbage after value for option "--set-mark".

Try `iptables -h' or 'iptables --help' for more information.
E0618 01:15:50.885247       1 service_endpoints_sync.go:343] Failed to verify and cleanup any mangle table rule to FMWARD the traffic to external IP due to Failed to cleanup iptables command to set up FWMARK due to running [/sbin/iptables -t mangle -C PREROUTING -d 192.168.20.180 -m tcp -p tcp --dport 80 -j MARK --set-mark 8370 <nil> --wait]: exit status 2: iptables v1.8.3 (legacy): MARK: trailing garbage after value for option "--set-mark".

**Comment by caesarcxiv** [comment]
changing daemonset to pull cloudnativelabs/kube-router:v0.3.1 resolves the issue

**Comment by zerkms** [comment]
And now after upgrading to rc5 then reverting to rc4 I have issues with number of iptables rules/chains:

```
# iptables -L -nvx| wc -l
12774
```
```
E0618 02:31:03.689136       1 network_policy_controller.go:270] Aborting sync. Failed to cleanup stale iptables rules: Failed to delete the chain KUBE-POD-FW-3NSXEQXBMYGXZKWG due to running [/sbin/iptables -t filter -X KUBE-POD-FW-3NSXEQXBMYGXZKWG --wait]: exit status 1: iptables: Too many links.
E0618 02:32:20.469837       1 network_policy_controller.go:270] Aborting sync. Failed to cleanup stale iptables rules: Failed to delete the chain KUBE-POD-FW-3NSXEQXBMYGXZKWG due to running [/sbin/iptables -t filter -X KUBE-POD-FW-3NSXEQXBMYGXZKWG --wait]: exit status 1: iptables: Too many links.
E0618 02:33:37.195086       1 network_policy_controller.go:270] Aborting sync. Failed to cleanup stale iptables rules: Failed to delete the chain KUBE-POD-FW-3NSXEQXBMYGXZKWG due to running [/sbin/iptables -t filter -X KUBE-POD-FW-3NSXEQXBMYGXZKWG --wait]: exit status 1: iptables: Too many links.
```

**Comment by murali-reddy** [comment]
@zerkms Please try https://github.com/cloudnativelabs/kube-router/releases/tag/v1.0.0-rc6 it has fix. Reopen if you are still facing the issue.

> And now after upgrading to rc5 then reverting to rc4 I have issues with number of iptables rules/chains:

see the release notes for rc5. rc4 and rc5 has changes that are incompatile. You need flush the filter table.
