### ISSUE TITLE
Support traffic shaping in CNI

### ISSUE THREAD

**Issue by kvaps** [cloudnativelabs/kube-router#954]
k8s 1.12 added a support for traffic shaping: kubernetes/kubernetes#63194 and kubernetes/community#1893. We should support it in the CNI plugin.

**Comment by murali-reddy** [comment]
@kvaps What is your expectation from kube-router? Update the manifests with `bandwidth` plugin? I belive you should be able to use traffic shaping CNI https://github.com/containernetworking/plugins/tree/master/plugins/meta/bandwidth just by chaining just as how `portmap` is used.

**Comment by kvaps** [comment]
Hi, if I remember it correct the mentioned bandwidth plugin has no tight integration with Kubernetes, and does not allow to set the bandwidth limit per pod via annotations.

**Comment by aauren** [comment]
kube-router currently only supports configuring upstream CNI plugins. If there is a way that we can help configure an already existing CNI plugin to support traffic shaping, that might be do-able, but given the breadth that kube-router already spans and the difficulty supporting that breadth I think that it would be a bad idea to add CNI plugin development to our existing stack.

If you can give some concrete details about what would be involved in configuring an already existing CNI plugin to do this shaping then I'd be willing to look into scheduling the work after the 1.2 performance release. Otherwise we'll probably end up closing this issue as something that kube-router cannot support at this time.

**Comment by aauren** [comment]
Closing as stale.
