### ISSUE TITLE
Can't find configuration for a new passive connection

### ISSUE THREAD

**Issue by Elegant996** [cloudnativelabs/kube-router#991]
**What happened?**
Cannot establish BGP peering with router when using a Virtual IP as the peer router IP.

**What did you expect to happen?**
For `kube-router` to establish BGP peering with the VIP and not attempt to peer with the router's real IP nor add it as a passive interface.

**How can we reproduce the behavior you experienced?**
1. Create a pfSense High Availability environment
2. Install FRR
3. Assign the interface VIP as the Router ID for BGP
4. Specify the VIP in `kube-router` using `--peer-routers-ips`

**System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): 1.0.1 (also occurs in 1.1.0 RC)
 - Kube-Router Parameters:
```
        - "--advertise-cluster-ip=true"
        - "--advertise-external-ip=true"
        - "--advertise-loadbalancer-ip=true"
        - "--bgp-graceful-restart=true"
        - "--cluster-asn=65480"
        - "--enable-cni=false"
        - "--enable-ibgp=true"
        - "--enable-overlay=true"
        - "--enable-pod-egress=false"
        - "--nodes-full-mesh=true"
        - "--peer-router-asns=65000"
        - "--peer-router-ips=10.0.30.1"
        - "--run-router=true"
        - "--run-firewall=false"
        - "--run-service-proxy=false"
```
 - Kubernetes Version (`kubectl version`) : 1.17.11
 - Cloud Type: on premise
 - Kubernetes Deployment Type: Kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 2 Nodes, 1 Master

**Logs, other output, metrics**
```
kube-router time="2020-09-23T17:45:10Z" level=info msg="Can't find configuration for a new passive connection from:10.0.30.2" Topic=Peer
```

**Additional context**
We are currently using pfSense with High Availability with FRR for BGP peering. The IP addresses of the routers are 10.0.30.2 and 10.0.30.3 with the VIP being 10.0.30.1. FRR is set to use the VIP as the Router ID but `kube-router` somehow recognizes the real IP of the current master router (e.g. 10.0.30.2) and attempts to peer with it instead of the VIP specified.

This issue does not occur using other BGP peering tools such as `metallb` or `calico` as they both respect the VIP and do not attempt to peer with the real IP of the master router.

**Comment by aauren** [comment]
@Elegant996 it looks like the issue here is that when your pfSense machines are establishing the peering connection they are using their internal IP rather than their VIP. Since those machines are configured for passive BGP sessions that means that they aren't even reaching out the kube-router, but rather waiting for kube-router which is configured as an active BGP speaker to establish the connection with the VIP, but then the response itself is coming from the interface that the individual machines own.

kube-router, and specifically gobgp which handles all of the BGP logic, will not accept this peer establishment flow because it is expecting the traffic from the neighbor-address that it was configured with (i.e. the VIP). This is also a security measure to ensure that random hosts are not peering with you and impacting your BGP state. If this is happening with calico and metallb and they accept it, and I can't imagine why they would as they should also not recognize the peering from an unknown IP address, I would consider this a bug in their functionality.

The above is just my guess based upon the log message. A full tcpdump of the BGP session establishment between the two hosts should be able to easily confirm this though.

I'm not super familiar with pfSense and their HA mechanisms, but I would imagine that you could just bond with both of the internal interfaces of the individual machines. Or you could look into how to improve the pfSense VIP usage so that pfSense would return traffic from the floating VIP that it received the traffic from rather than it's internal interface. However, I can confirm that we do the same thing using a different (non-pfSense) networking stack where we use a floating VIP to establish the BGP peering session from kube-router and it works fine.

**Comment by Elegant996** [comment]
Quick run down, pfSense uses a master/slave system. While the master is active, the services of the slave are not started. When the master goes down, the slave is promoted to master and starts its services.

In short, it isn't possible to peer with both 10.0.30.2 and 10.0.30.3 simultaneously because 10.0.30.3 does not start FRR while it is marked as slave.

While it is possible to just wait for the slave to come online after it takes over as master this somewhat negates the point of the VIP which does work with other services. This would point to `gobgp` being the outlier even if it is for a security measure.

I had originally discovered this issue about 2 months ago but resolved it by enabling `nodes-full-mesh`. It resurfaced recently with an update to FRR but couldn't find any changes from the git commits that altered behavior.

Given that it was working previously, it would seem that some part of `gobgp` permits the VIP or perhaps it's how FRR was presenting the VIP. That may require delving into the FRR logs and seeing what is transpiring on the other end.

**Comment by aauren** [comment]
I guess a couple of thoughts/questions come to mind:
- I looked really quick at the address and peering options that we have available to us through gobgp and through their issues and I don't see any obvious fixes for this that wouldn't allow all IPs to peer with kube-router, but I could be missing something, you're welcome to check as well
- Between working and not working did you change kube-router versions? If so what was the version before and after?
- Same question on the pfSense side.
- I think looking through the FRR logs would be helpful
- I would also take a tcpdump (or some other packet capture) of the peering exchange between kube-router and pfSense as it would tell you alot
- If it's possible to revert to a version that was working in a test environment, I would try that and take a similar look at the logs and the packet capture

**Comment by Elegant996** [comment]
@aauren Found the solution but still somewhat unsure of the cause. When configuring the neighbor in FRR, you can select the Update Source.

Update Source is set to Default but this would imply that it would use the interface address of the current master. Once changed to the VIP, pfSense and `kube-router` properly communicate through the desired address. Wonder why it was occassionally picking the VIP in the past...

In any case, this issue is now resolved :)

**Comment by aauren** [comment]
Glad you were able to figure it out! I'm sure this will help any other pfSense users as well. Thanks for the update!
